### ISSUE TITLE
Fps Drop on not sleeping [Performance Issue]

### ISSUE THREAD

**Issue by pohihihisocks** [Stereowalker/Survive#10]
I'm assuming the debuff's you get are looped so it create's a huge amount of lag for potato pc's can you consider making the debuffs like updates per 30 secs and the debuff lasts 1 minute? so it won't lag anymore?

**Comment by Puszkaa** [comment]
Hi, i come here with the same issue. From my experience i can say that is more like graphic issue. I use this mod on my laptop which has two graphic cards. For playing minecraft i use weaker one and i have huge fps drop when it comes to first debuff (60 to 20). On better graphic card this mod works great. I think that might help a bit to solve this problem. :)

**Comment by Stereowalker** [comment]
What version of the mod are you using?

**Comment by Puszkaa** [comment]
I've tried 1.4.1 and 1.5.3. Same issue on both.

**Comment by Stereowalker** [comment]
After a lot of trial and error, I believe I've been able to amend this issue in 1.16.1 so as a result, I'm closing this issue

**Comment by Stereowalker** [comment]
If you feel otherwise, please comment
