### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Warbringer12** [Stereowalker/Survive#100]
forge: 1.16.5-36.1.2
survive: 1.16.5-3.1.7
[crash-2021-03-29_19.08.29-fml.txt](https://github.com/Stereowalker/Survive/files/6225681/crash-2021-03-29_19.08.29-fml.txt)
something in your unionlib mod is causing this to happen cause as soon as i downgraded unionlib to 1.16.5-3.2.6 it works fine

**Comment by Stereowalker** [comment]
Please update Survive to 3.2.0

**Comment by Warbringer12** [comment]
ah wasn't out when I tried it. thanks
