### ISSUE TITLE
Failed to process update information

### ISSUE THREAD

**Issue by sfiomn** [Stereowalker/Survive#108]
I get this error on the update at the run of the server.

I don't know if it's a big deal:

https://gist.github.com/sfiomn/880622953adda6b9026d0a30126fe4f3

**Comment by Stereowalker** [comment]
It's nothing to worry about. You only got that because you didn't have internet when it tried to version check

**Comment by sfiomn** [comment]
And if I had an internet connection ? Should I worry about ?
