### ISSUE TITLE
Loading survive mod error

### ISSUE THREAD

**Issue by Mnigos** [Stereowalker/Survive#113]
Hello, I installed survive and serene seasons mods. I'm on Forge 1.16.5-36.1.13(Latest), and got that error trying to load minecraft.

Survive only supports sereneseasons 4.0.0.80 or above 
Currently, sereneseasons is 1.16.5-4.0.1.91

**Comment by Lupinarius** [comment]
I ran into the same issue. looks like it could be a change in the way serene seasons versions their mod, but I'm not well enough versed to be sure.

**Comment by Stereowalker** [comment]
Does running version 4.0.0.80 of serene seasons cause this issue?

**Comment by Mnigos** [comment]
> Does running version 4.0.0.80 of serene seasons cause this issue?

I tried to run it with 4.0.0.80 but then forge see it as 4.0.0.76 version

**Comment by MAGGen-hub** [comment]
AAAHhhh!!!! That forge makers done something horrible to forge again!!! Just downgrade your forge version to 36.1.4 and everything will be back to normal... Why the heck all my mods start to produce stupid crashes after EACH forge update??? Sorry for my anger and bad english, but I just tired from all these infinite crashes...

**Comment by Mnigos** [comment]
yep this mod doesn't work with latest forge.

**Comment by MAGGen-hub** [comment]
Heh, I got the same problem with Create mod on 1.16.4 with latest forge. Only 35.1.36 forge version works corectly... And here we go again...

**Comment by ghost** [comment]
Confirming that the cause is probably Forge because i played on Forge 36.1.10, Survive 3.2.2 and Serene Seasons 4.0.1.91 with no problems at all, after updating it crashes.

**Comment by Stereowalker** [comment]
Fixed
