### ISSUE TITLE
thirsty and armor gui interfere

### ISSUE THREAD

**Issue by AlleCraft** [Stereowalker/Survive#12]
thirsty and armor gui interfere
![2020-06-20_23 25 49](https://user-images.githubusercontent.com/51967599/85211868-9d3b8a00-b34d-11ea-9341-7393cb241905.png)
![2020-06-20_23 26 06](https://user-images.githubusercontent.com/51967599/85211869-9e6cb700-b34d-11ea-94fd-2314a1d87b9f.png)

**Comment by Stereowalker** [comment]
Why is the armor bar on the right side of your gui ?

**Comment by rgt002** [comment]
i'm getting this too when i play with other mods. if it's only this mod installed, and its library dependency, the armor hud is in its normal location

**Comment by rgt002** [comment]
i found the issue on my end - levelhearts mod. it moves the armor hud over the hunger bar to allow for a second row of heart containers

**Comment by Stereowalker** [comment]
Is there an option in levelhearts to restore the armor gui to its original position?

**Comment by Cobyt3** [comment]
Have you ever found out a fix for that?

**Comment by Stereowalker** [comment]
It's sorta fixed on more recent versions of Minecraft

**Comment by Cobyt3** [comment]
okay, sadly I am making a Modpack on 1.16.5 because there are a lot of dependencies I need, so I have to find a workaround. Thank you anyways
