### ISSUE TITLE
New Version make this "cannot load please safe mod" screen [Image not mine] can someone help me with that?

### ISSUE THREAD

**Issue by Sacri-Pan** [Stereowalker/Survive#135]
![image](https://user-images.githubusercontent.com/74361905/122567796-5c05b500-d049-11eb-90a5-77043e7a690f.png)

**Comment by CubeToPlay** [comment]
I think the problem is the newest version of UnionLib.

**Comment by Stereowalker** [comment]
can I have your logs? preferably your latest.log file

**Comment by XxInvictus** [comment]
[UnionLib_3.3.3_Survive_3.3.2_Crash.log](https://github.com/Stereowalker/Survive/files/6681671/UnionLib_3.3.3_Survive_3.3.2_Crash.log)
Here is my server log, Union lib 3.3.3 and Survive 3.3.2

**Comment by rtxyd** [comment]
@Sacri-Pan This problem may caused by remaiming data of delete mod. I solve the problem with "NBT explorer" to change "level.dat" of the very save. 
this is the github entry of the tool.
https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win

**Comment by rtxyd** [comment]
You should back up your save before operate. Delete all in following marked drop-down lists with "NBT explore", and re-enter the save it should be solved.
![360截图20210620185952175](https://user-images.githubusercontent.com/65117312/122671573-f573c900-d1f9-11eb-8f25-822c81e8248c.jpg)
![360截图20210620190002087](https://user-images.githubusercontent.com/65117312/122671577-f6a4f600-d1f9-11eb-8f05-853bb1649fff.jpg)
![360截图20210620190014216](https://user-images.githubusercontent.com/65117312/122671582-fa387d00-d1f9-11eb-9db5-09caf708f740.jpg)
![360截图20210620190045526](https://user-images.githubusercontent.com/65117312/122671589-0290b800-d1fa-11eb-85ce-03ebcd5d8fe2.jpg)

**Comment by rtxyd** [comment]
You should back up your save before operation. Delete all in following marked drop-down lists, and re-enter the save, it should be solved.
![360截图20210620185952175](https://user-images.githubusercontent.com/65117312/122671895-551ea400-d1fb-11eb-9b10-2dcf350d2dc3.jpg)
![360截图20210620190014216](https://user-images.githubusercontent.com/65117312/122671896-56e86780-d1fb-11eb-92c6-95b9e66904ef.jpg)
![360截图20210620190045526](https://user-images.githubusercontent.com/65117312/122671897-5780fe00-d1fb-11eb-95a0-f8c297e3269e.jpg)
![360截图20210620191113781](https://user-images.githubusercontent.com/65117312/122671899-58199480-d1fb-11eb-9d93-f64d3777617e.jpg)

**Comment by Miszelka** [comment]
seems like the problem is with the latest version of UnionLib and/or your launcher. Try downgrading UnionLib to 3.3.2 and update your launcher to forge 36.1.2, at least. This worked for me

**Comment by Stereowalker** [comment]
Run Survive 3.3.2 with UnionLib 3.3.2. Changes were made to UnionLib 3.3.3 that are not currently compatible with the latest version of Survive
