### ISSUE TITLE
Server crashed on launch

### ISSUE THREAD

**Issue by StarchierOrb** [Stereowalker/Survive#136]
Survive version: 3.3.2 (latest)
UnionLib version: 3.3.3 (latest)
Forge version: forge-1.16.5-36.1.24

Server does not start correctly and show  Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
(I didn't use any custom databacks.)

Error log:
https://paste.ubuntu.com/p/NJysMhyQTt/

**Comment by StarchierOrb** [comment]
But it seems work with UnionLib 3.3.2

**Comment by Stereowalker** [comment]
There was a major change in UnionLib 3.3.3
When Survive is updated to version 3.3.3 please use this version of UnionLib
