### ISSUE TITLE
[BUG] Got an error while creating a world

### ISSUE THREAD

**Issue by Mnigos** [Stereowalker/Survive#137]
![image](https://user-images.githubusercontent.com/56691628/122998168-04e74380-d3ad-11eb-89b0-f90fd65d4f80.png)

While i trying to load/create world with survive mod in got this error. I tried to install recommended and latest versions of forge and that didn't help me. 
[latest.log](https://github.com/Stereowalker/Survive/files/6697352/latest.log)

**Comment by Stereowalker** [comment]
Please use UnionLib 3.3.2. You can update to this version after Survive is updated to 3.3.3

**Comment by Mnigos** [comment]
I tried UnionLib 3.3.3 and 3.3.2 and Survive 3.3.2, 3.3.1, 3.2.2, 3.0.11. With 3.0.11 I got another error and cannot even load to main menu.
