### ISSUE TITLE
Errors in currently selected datapacks prevented the world from loading.

### ISSUE THREAD

**Issue by imperialR3D** [Stereowalker/Survive#139]
I've been trying to put together a modpack for a while now that includes the Survive mod. However, I ran into a problem when trying to create a world with the modpack. An error would always pop up when trying to create a world saying: "Errors in currently selected datapacks prevented the world from loading." It gave me an option to either go back to the title screen to fix the issue manually or to launch the game in "Safe Mode". Safe mode never worked, no matter how many times I clicked the button it didn't seem to do anything at all.

In any case, I did some testing by going through and adding each of my mods one by one to find which mod was causing the error and found that this error was caused by the Survive mod. I wanted to know whether this was a compatibility issue with my other mods so I also tried creating a world with just the Survive mod installed, which gave me the same error. I do not have any datapacks installed other than those that come with the mods so that couldn't be interfering either.

I also tried installing previous versions of Survive which all gave me the same issue. I even borrowed my roommate's computer to test it out there and it still had this issue. I even tried to install Survive by both dropping it into the mods folder and by installing directly from the Curseforge loader, neither of which worked. I just don't know what to do at this point. I feel like I've exhausted all of my options for fixing this issue myself and I would really like to use this mod for my modpack. Is there anything I can do on my end or is this an issue with the mod?

I have attached my latest debug log in case it helps with figuring out the issue:
[latest.log](https://github.com/Stereowalker/Survive/files/6711463/latest.log)

**Comment by GhostWing404** [comment]
i've been having the same problem and i really need the survive mod because i already had a bunch of world's with the mod loaded and i cant play them until this issue gets fixed

**Comment by Furiousbot5** [comment]
I've been having this problem as well I hope that they fix this or unless there is a way to fix this problem

**Comment by Stereowalker** [comment]
Run Survive 3.3.2 with UnionLib 3.3.2. Changes were made to UnionLib 3.3.3 that are not currently compatible with the latest version of Survive
