### ISSUE TITLE
[enhancement] Config option for thirst tick speed/thirst ticks faster when sprinting

### ISSUE THREAD

**Issue by WaldoTheRanger** [Stereowalker/Survive#14]
I've noticed that unlike hunger, thirst decreases at the same rate regardless of the player's movement.
Personally I find this speed to be a bit too slow, so I would like the ability to change it.\
I would also like it to work more like food, where it decreases more when jumping and/or sprinting
Config options for both of those would be awesome.

Thanks for the mod. keep up the good work. I hope I'm helping.

**Comment by WaldoTheRanger** [comment]
Thanks for adding the jumping calculations.

**Comment by 5t3v3n** [comment]
An option so set the rate that thirst ticks down would be absolutely amazing Please Please PLEASE add this

**Comment by WaldoTheRanger** [comment]
Adding the same for hunger would be awesome too, but I understand if that's out of the scope of the mod.
