### ISSUE TITLE
[Bug] Game tries to make you run the datapacks in safemode

### ISSUE THREAD

**Issue by zndrmn** [Stereowalker/Survive#141]
**World Generation Settings:**
_https://imgur.com/xmFjSmq_
**Error Message**
_https://imgur.com/RrYViKs_
**Logs:**
No logs were made / updated
**Notes:**
Configs have not been changed and where freshly generated.
I know this is either a survive problem / Union Lib problem because the problem doesn't occur.
**Mod List:** 
_https://gist.github.com/zndrmn/255ce792d871e3a6a925f4b89dd63220_
And also on the latest versions of Union Lib and Survive

**Comment by Vxoll** [comment]
Same is happening to me, after removing the most recent versions of survive, the game seems to be working again.
Any clue on why this is happening and how to fix this?

**Comment by zndrmn** [comment]
I think its a Union Lib problem. . .
Union Lib 3.3.2 + Survive 3.3.2 seems to work fine but as soon as I use Union Lib version 3.3.3 the problem occurs.
Forge Version : **1.16.5-forge-36.1.32**
Optifine Version : **OptiFine_1.16.5_HD_U_G8**
_( WORKING VERSION )_
**Union Lib 3.3.2** + _Survive 3.3.2_
_( NOT SO WORKING VERSION )_
**Union Lib 3.3.3** + _Survive 3.3.2_

**Comment by Vxoll** [comment]
Huh interesting, after a bit of research on this topic i found that it was something related to some sorth of datapack or something similar to this that was or poorly coded or outdated, this still rather confusing to me but thanks for your explanation.

Adios.

**Comment by NixityNull** [comment]
I have the same problem, and I don't have any datapacks installed. 

Honestly, survive has just been a mess since the beginning. First the thirst had problems, then certain items weren't craftable... Between this and tough as nails, what is with 1.16 thirst/temperature mods not working properly.

**Comment by Seaweed14** [comment]
I'm still having this issue with Survive 3.3.2 and UnionLib 3.3.7

**Comment by Stereowalker** [comment]
Use UnionLib 3.3.7 with Survive 3.4.2

**Comment by Stereowalker** [comment]
It was bad versioning on my part that caused this whole mess. I had made some changes in UnionLib that caused the datapack issue, and rather than version it as 3.4.0, I instead versioned it as 3.3.3
