### ISSUE TITLE
Celsius to Fahrenheit conversion is way off

### ISSUE THREAD

**Issue by TheGamersBrew** [Stereowalker/Survive#144]
-Your conversion of Celsius to Fahrenheit is way off at the hottest point next to lava you have it at 39.49c which is 103.08f but when you turn it to Fahrenheit mode when you are next to lava it shows up a 71.49f. 

-Also would it be possible for you to turn off the decimal place on the number mode for Temperatures as it would allow for better placement in the hud area. (see picture 3 as to how it currently fits)

![image](https://user-images.githubusercontent.com/77638191/125562718-e9b98842-0aae-4f5f-a1e0-ab70515eaf83.png)
![image](https://user-images.githubusercontent.com/77638191/125562972-351db3de-39e8-4c18-b7be-bb414ceb9304.png)
![image](https://user-images.githubusercontent.com/77638191/125563347-6e6d0558-caa5-4f52-bb99-1732df5eaec7.png)

**Comment by Stereowalker** [comment]
Fixed, thanks for pointing it out
