### ISSUE TITLE
Can have both Hyperthermia and Hypothermia at the same time

### ISSUE THREAD

**Issue by TheGamersBrew** [Stereowalker/Survive#145]
While testing out the mod found that you can have both Hyper and Hypothermia at the same time. While the effects of one over the other do not last long it would reason to believe that you should not have one at the same time as another. This being the case I suggest you make it so you can't have both at the same time and rather they transition to each other. Also increase the rate of decay of the effects so you can't just toss down a bucket of lava stand next to it and be instant fix for cold. 

![image](https://user-images.githubusercontent.com/77638191/125565395-f784b711-82eb-4226-8bac-b6c62ade998f.png)

**Comment by Stereowalker** [comment]
Will be fixed next release
