### ISSUE TITLE
A bug that causes inability to enter the world

### ISSUE THREAD

**Issue by kinhirozane** [Stereowalker/Survive#146]
You can enter the game, there is no crash log, and the launcher log does not show that it is a Survive problem, but when you want to enter the world, you will be prompted with an incorrect datapack and cannot be entered. Finally, after excluding 246 mods, it was found that it was a survive problem. Since there is no related log record, I will not post the pastbin link.

mc version: 1.16.5
forge: 36.1.23
survive: 1.16.5-3.3.2

**Comment by llMilkll** [comment]
You need to use Unionlib version 3.3.2 instead of Unionlib version 3.3.3

**Comment by kinhirozane** [comment]
ok let me try

**Comment by Tyrius1** [comment]
also experienced this issue. https://pastebin.com/qkbtuQJw
after backdating UnionLib to 3.3.2 the world hung at 100% first attempt to launch
Then loaded fine 2nd, 3rd and 4th times
and hung again at 100% on 5th attempt.
[latest.log](https://github.com/Stereowalker/Survive/files/6857588/latest.log)

MC 1.16.5
forge 36.1.32
survive 3.3.2
union lib during datapack issue: 3.3.3
union lib during world load lock up issue: 3.3.2

What is the minimum forge build for unionlib 3.3.3?
