### ISSUE TITLE
Stamina dropping oddly too fast wearing Netherrite Armor

### ISSUE THREAD

**Issue by GlorShmi** [Stereowalker/Survive#147]
so idk if its 100% a bug or intended but literally after a minute or less wearing netherrite armor you lose all your stamina and It wont let me disable the armor weights in the config :(   (I am playing on a server so maybe thats why it wont let me disable it in the config?)

**Comment by Stereowalker** [comment]
It's an intended feature. Enchant the armor with featherweight/weightless to reduce/remove the weight of the armor
