### ISSUE TITLE
[BUG] Crashed when trying to see an Enchanted sword

### ISSUE THREAD

**Issue by dylan-jara** [Stereowalker/Survive#151]
**Describe the bug**
[It seems that there is an incompatibility with the Quark mod, when wanting to see an Enchanted sword, placing the cursor on it crashes. :(.]

**Logs**
[[crash-2021-07-26_15.03.54-client.txt](https://github.com/Stereowalker/Survive/files/6881459/crash-2021-07-26_15.03.54-client.txt)]

**To Reproduce**
[Steps to reproduce the behavior:
1. Enchant a sword or seek an enchanted one
2. Place the cursor over the item
3. See error]

**Expected behavior**
[that will show the description of the item and do not crash the minecraft.]

**Screenshots**
[There is no need for photos, because if I try to do it, it crashes.]

**Minecraft Environment:**
 - Forge Version: 1.15.2-forge-31.2.50
 - UnionLib Version: UnionLib-1.15.2-3.2.6
 - Survive Version: Survive-1.15.2-3.1.7
 - Quark Version: Quark-r2.1-245

**Additional context**
[is there any way to fix it, still anyway send a bug report to the quark mod creator on github, or is there any other mod like survive that contains the cold, heat and thirst for 1.15.2?

**Comment by Stereowalker** [comment]
Will be fixed. Thanks for pointing it out
