### ISSUE TITLE
(Suggestion) Ability To Adjust Summer/Winter Severity

### ISSUE THREAD

**Issue by JakeSublime** [Stereowalker/Survive#153]
I would like summers and winters to be more impactful on the player. So far, i havent really been forced to shelter to protect from heat/cold. I wish there was a config option to make summer and winter separately more or less intense. 

Edit: Im using Serene Seasons. So maybe an adjustor for making cold and hot regions more intense, not necessarily summer and winter.

**Comment by Stereowalker** [comment]
It's a feature I consider adding alongside support for better weather, but that will be in 1.17
