### ISSUE TITLE
Game crash 1.16.5-3.4.2

### ISSUE THREAD

**Issue by Seaweed14** [Stereowalker/Survive#154]
Game crashes when loading Survive 3.4.2, even with Unionlib 3.3.7

Crash log seems to indicate Create as the issue. When Create is removed, issue is blamed on Comforts. But when I remove Survive, crash does not occur. Seems to move error from one mod to the next.

Crash log from when Create is in mod folder:
[crash-2021-08-03_14.16.29-fml.txt](https://github.com/Stereowalker/Survive/files/6926929/crash-2021-08-03_14.16.29-fml.txt)

Crash log from when Create is removed:
[crash-2021-08-03_14.37.06-fml.txt](https://github.com/Stereowalker/Survive/files/6926930/crash-2021-08-03_14.37.06-fml.txt)

Crashlog from when Comforts is removed:
[crash-2021-08-03_14.43.09-fml.txt](https://github.com/Stereowalker/Survive/files/6926932/crash-2021-08-03_14.43.09-fml.txt)

Mod List:
Quark Oddities
Astral Sorcery
UnionLib
Infernal Expansion
JEI
Druidcraft
Abnormals core
Buzzier Bees
Macaw's windows
Caelus API
Clumps
Xaero World map
Connected textures
cooking for blockheads
Citadel
Tumbleweed
Traveler's Backpack
Serene Seasons
Decorative Blocks
Environmental
Better Animals Plus
Bookshelf
Simple planes
Custom Signposts
Macaw's doors
mapper base
mahou tsukai
ice and fire
waila
Snow!
Kiwi
FPS reducer
bloodmagic
supplementaries
better end forge
cuneiform
dynamis surroundings
selene
chocolate
upgrade aquatic
farmer's delight
farmer's delight cookbook
repurposed structures
embellishcraft
biome's o plenty
embellishcraft BoP
Valhelsia structures
macaw's trapdoors
towers of the wild
simplefarming
botania
astrikor Carts
Ultimate car mod
flywheel
curios API
Patchouli
Origins
Xaero's minimap
Roadstuff
extended lights
Polymorph 
autoreglib
quark
tough as nails
survive
simply tea
terra incognita
regrowth
ftb ultimine
obfuscate
mrcrayfish vehicle mod
desolation
builder's crafts and addition
worldedit
Macaw's roofs
Architectury
appleskin
chisel
observerlib
macaw's furniture
spice of life:carrot
cloth config
aquaculture 2
small ships
custom starter gear
valhelsia core
effortless building
better foliage

**Comment by Stereowalker** [comment]
Sorry for taking too long to reply. I've looked at the logs and I would advise removing tough as nails. This mod and that mod are trying to apply patches to the same method which is causing Mixin to bug out and in turn cause your game to crash

**Comment by Seaweed14** [comment]
No worries. Thanks for getting back to me! I will definitely do that.

**Comment by Stereowalker** [comment]
Also, it doesn't look like this will be addressed on TAN's side, so I'm going to flag it as incompatible with this one
