### ISSUE TITLE
JEI isnt showing up

### ISSUE THREAD

**Issue by rjulib00** [Stereowalker/Survive#155]
with survive installed, JEI isnt showing the GUI (no, is not hidden, i check it, and use the keybinds to hide/show it)

**Comment by Stereowalker** [comment]
What version of JeI, Survive, UnionLib and Forge are you using?

**Comment by rjulib00** [comment]
> What version of JeI, Survive, UnionLib and Forge are you using?

its working with the lastest update of survive, so i guess its fixed
