### ISSUE TITLE
Crashing when I join a singeplayer world.

### ISSUE THREAD

**Issue by Voidatron** [Stereowalker/Survive#16]
Pretty simple issue, I crash after the game tries to load me into my sing player world for about 50 seconds. I will give you the crash report.
[crash-2020-07-30_00.54.23-server.txt](https://github.com/Stereowalker/Survive/files/5002864/crash-2020-07-30_00.54.23-server.txt)

**Comment by Stereowalker** [comment]
Update forge to 32.0.98

**Comment by Voidatron** [comment]
[crash-2020-07-30_22.07.12-server.txt](https://github.com/Stereowalker/Survive/files/5004627/crash-2020-07-30_22.07.12-server.txt)

I updated the forge but it did crashed. I made it a little bit further though, the game closed itself this time instead of freezing.

**Comment by Voidatron** [comment]
I fixed it, I think it was my optifine causing the issue. Thank you for helping me out today.
