### ISSUE TITLE
Your path for datapacks is incorrect

### ISSUE THREAD

**Issue by IdealIdeas** [Stereowalker/Survive#163]
It says to modify thirst of items I need to create a datapack with the file structure labeled in the description, which does not work.
In the mod description it says the file path is:
minecraft/survive_drinks/items/steak.json

After peering into the jar file and copying the same file structure as in your jar file, it now works flawlessly!

the correct datapack path is
data/minecraft/survive_modifiers/consumables/items/apple.json

The full path being:
datapacks/YOUR DATAPACK NAME HERE/data/minecraft/survive_modifiers/consumables/items/apple.json

**Comment by Stereowalker** [comment]
Thanks, Updated
