### ISSUE TITLE
Fire resistance and Hyperthermia. 1.16.5

### ISSUE THREAD

**Issue by MinecraftGuy12364** [Stereowalker/Survive#166]
I don't understand how this is. If I have fire resistance, isn't that supposed to mean that hyperthermia goes away?

**Comment by Stereowalker** [comment]
Well yes, but actually no. Although fire resistance will prevent you from catching fire, It doesn't change the fact that you are still getting affected by all the heat from the said fire. As a way to alleviate your pain, I'll be making all fire resistance potions provide a little heat resistance. Hope that helps, good day
