### ISSUE TITLE
Disable survive elements for specific people

### ISSUE THREAD

**Issue by hakasapl** [Stereowalker/Survive#168]
Hi,

I'm working on a modpack that uses Origins:forge to allow players to select their race at the start of the game. Some races, such as "Blazeborn" allow the player to swim in Lava. This works as intended, but they end up dying from heat as a result of the survive mod. Is there a way to disable elements of this mod for specific people? If not I'll see if I can make a PR that will add this feature.

**Comment by Stereowalker** [comment]
Hello, there already is the heat resistance power added to the blazeborn origin

**Comment by Stereowalker** [comment]
This was added in the 1.16.5 version of Minecraft

**Comment by hakasapl** [comment]
Thanks for the quick response. This is added on the Survive mod side or the Origin mod side? Just confused on the implementation as the blazeborn race dies very quickly due to heat in my modpack (Using 1.16.5 version of both mods)

**Comment by hakasapl** [comment]
Okay I figured some things out. I want to extend this support to custom origins so I submitted a quick PR: https://github.com/Stereowalker/Survive/pull/169

Thanks!
