### ISSUE TITLE
Two temperature bars when moved down Y axis

### ISSUE THREAD

**Issue by D-Bigboy-302** [Stereowalker/Survive#17]
Survive Version: 1.15.2-1.6.3
Forge Version: 1.15.2-31.2.33

When temperature display mode is set to "BAR" in the client config and moved down, there are two bars.

![2020-07-31_08 57 21](https://user-images.githubusercontent.com/61896885/89039405-dbd24600-d2f6-11ea-9e1f-1ac036e6cfe3.png)

Also, since I am here, would it be possible to add an option to move the thirst bar as well? Didn't see any options in any of the configs, would be nice to have.

Regardless, thank you for your time!

**Comment by Stereowalker** [comment]
I'm no longer working on the 1.15.2 version of the mod as I've ported the project to 1.16.1, so I won't be able to fix it on that version of minecraft

**Comment by D-Bigboy-302** [comment]
Aw... Alright well thank you for your time! :)
