### ISSUE TITLE
OptiFine incompatibility. 1.18

### ISSUE THREAD

**Issue by XxFallenAngelxX** [Stereowalker/Survive#181]
Game Crashes on startup, when Optifine (Forge) + Survive (Forge) are installed. 
(Latest version of Forge, Optifine and Survive)

https://pastebin.com/ksYDsEdg

https://pastebin.com/sN84NbK1

**Comment by Cursedth** [comment]
I think similar issue to this one.

--Minecraft crash log--
[latest.log](https://github.com/Stereowalker/Survive/files/7695696/latest.log)
--end crash log--

Ran UnionLib without Survive, no issues.

**Comment by Stereowalker** [comment]
I doubt this is a Survive related error

**Comment by zachsai** [comment]
The incompatibility comes from unionlib

**Comment by zachsai** [comment]
unionlib + optifine breaks the game

**Comment by BeastRedex** [comment]
Yes please fix this for r1.18

**Comment by Stereowalker** [comment]
fxd
