### ISSUE TITLE
Safe Mode Screen Error

### ISSUE THREAD

**Issue by FluffyTheFurry** [Stereowalker/Survive#185]
So Survive mod is making this issue with Safe Mode screen I tried it without Survive mod and worked completely fine with it when creating new world or joining old world, it shows the screen ![Capture](https://user-images.githubusercontent.com/95755960/145685875-1303c0cc-3f4c-438b-a9d6-b0f9e8db6aed.PNG)

**Comment by Stereowalker** [comment]
If you're running the latest version of Survive on 1.18, then I can assure you that the fault is not from Survive as this is an unfortunately very common bug. What I suggest you do is check every mod you've installed to ensure that it isn't the one preventing Survive from loading its datapacks

**Comment by Stereowalker** [comment]
The same goes for 1.17

**Comment by FluffyTheFurry** [comment]
Okay
