### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by ekaraca2006** [Stereowalker/Survive#187]
I don't know why but with the new version of union lab: UnionLib-1.18.1-6.1.6-Forge.jar and with the newest version of survive: Survive-1.18.1-6.0.1.jar my server crashes. Minecraft launches fine and union lib seems to functioning but when i try to open my server it crashes and i just wanted to get this issue addressed.

**Comment by Stereowalker** [comment]
Can you paste the crash log

**Comment by ekaraca2006** [comment]
there was an update to unionlib and now its working fine

**Comment by Stereowalker** [comment]
Thank goodness
