### ISSUE TITLE
Still crashing from breaking blocks.

### ISSUE THREAD

**Issue by Voidatron** [Stereowalker/Survive#19]
I cannot seem to break blocks without crashing even after the update. I have attached the crash report.
[crash-2020-08-06_22.21.26-client.txt](https://github.com/Stereowalker/Survive/files/5038974/crash-2020-08-06_22.21.26-client.txt)

**Comment by Stereowalker** [comment]
It's an issue from UnionLib.

**Comment by Voidatron** [comment]
Should I try to use an older version of UnionLib?

**Comment by Stereowalker** [comment]
Update it to 2.1.0

**Comment by Voidatron** [comment]
Still broken 
[crash-2020-08-07_00.31.14-client.txt](https://github.com/Stereowalker/Survive/files/5039319/crash-2020-08-07_00.31.14-client.txt)

**Comment by Stereowalker** [comment]
Still broken in 2.2.0?

**Comment by Voidatron** [comment]
It looks like it worked, I crashed a few times just from logging in, but after trying a different world and breaking a block in survival, and then switching to the other one I was trying in the first place it worked fine. Thanks for the help. I'll let you know if anything else happens with another ticket.
