### ISSUE TITLE
[Bug] Serious lags during respawn

### ISSUE THREAD

**Issue by EnderLiquid** [Stereowalker/Survive#193]
**Minecraft Version**
1.18.1

**Loader Version**
Forge 39.0.19 , Forge 39.0.44 and Forge 39.0.55

**Mod Version**
Survive-1.18.1-6.1.2

**Issues**
About forty mods was loaded in my game.It runs smoothly until I died in game. As soon as I clicked the Respawn botton,the game screen stucked and the window showed that my game didn't respond.The serious lag lasted for minutes.Below is my test result.
![2022-01-22 172833](https://user-images.githubusercontent.com/81964663/150633064-86c22df0-74a7-481c-806f-a33aa29dc944.png)
I'm sure that one of the reason why the lags were caused is this mod,and keep finding other possible reasons.
Here is something that may help fix.

Information when holding Shift+F3:
"ScheduledExecutables" takes most of computing power while respawn.The lags may be due to it.

Mod config:
I just disabled armor weight.

Server output during respawn:
[14:29:28] [Server thread/INFO]: Skipping update from removed player 'ServerPlayer['Hydroxyl'/200, l='ServerLevel[world]', x=-0.30, y=64.00, z=-29.49, removed=KILLED]'

My mod list:
![2022-01-22 172822](https://user-images.githubusercontent.com/81964663/150633066-67777199-9ac6-4d3c-98b9-f886cad5d158.png)

**Comment by Stereowalker** [comment]
Could you reproduce this issue and then send your `latest.log` file?

**Comment by EnderLiquid** [comment]
[2022-01-21-5.log](https://github.com/Stereowalker/Survive/files/7920197/2022-01-21-5.log)
This is the log on my server.My client even crashed because of the lag before successful respawn.

**Comment by Stereowalker** [comment]
`[13:55:07] [Server thread/INFO]: Hydroxyl was shot by Skeleton`
`[13:58:02] [Server thread/INFO]: Hydroxyl was slain by Spider`

How?

**Comment by EnderLiquid** [comment]
As what it said,in survive mode in the overworld.What's more information do you want?The lags aren't influenced by the way I die seemingly.

**Comment by Stereowalker** [comment]
Does the latest update fix your issue?

**Comment by MMVVMM** [comment]
Close it.I believe this is a small probability event that is difficult to reproduce by others. Anyway, your mod works well alone. Thank you for your help and your fantastic mod.
