### ISSUE TITLE
Problems with JEI

### ISSUE THREAD

**Issue by Parciwal** [Stereowalker/Survive#196]
You can only craft a purified water bottle with an uncraftable potion. This should be fixed.  At least in JEI. There are quite a few problems with JEI, you should look into that.
![water bottle](https://user-images.githubusercontent.com/78496745/151223620-7e4b66dc-4b78-4262-84f4-b00b8faaa5a0.PNG)

**Comment by Stereowalker** [comment]
Fixed in 6.1.5
