### ISSUE TITLE
Disabling Temperature should remove the enchantments from the table

### ISSUE THREAD

**Issue by demon112** [Stereowalker/Survive#198]
Ive been using this thing for a while and the amount of times i have gotten cooling or warming when i dont even have the feature on is maddening. Its either WAY too common or the game hates me i cannot even find feather falling let alone every other modded enchantment i have.

**Comment by Stereowalker** [comment]
When you disable it, you have to close and reopen the game so that the enchantments don't load

**Comment by demon112** [comment]
They are still there
