### ISSUE TITLE
Mod crash on 1.18.1

### ISSUE THREAD

**Issue by simYoung772** [Stereowalker/Survive#201]
Mod crashing on mc forge 1.18.1-forge-39.0.76. If the remove this mod from the mod folder, the clash disappears, so there seems to be a problem with the survive mode. Mod version is Survive-1.18.1-6.1.7.

Crash message:
"This crash may be caused by an invalid Java Runtime configuranation. Check  any custom configuranation settings.
Exit Code: 1"

What should I do?

**Comment by Hozq** [comment]
Having this issue as well

**Comment by Hozq** [comment]
Update: make sure you have the latest unionlib installed as well with the correct loader, fabric/forge whatever you use. Worked for me

**Comment by simYoung772** [comment]
It was by unionlib, Unionlib was febric version. Thank you.
