### ISSUE TITLE
Missing enchantments

### ISSUE THREAD

**Issue by Hozq** [Stereowalker/Survive#204]
Basically my server has 2 extra enchantments that my client doesn't have. Specifically 
![image](https://user-images.githubusercontent.com/99619566/154744552-2ae2e590-f456-441c-91d6-723e17ea4b96.png)

I've tried redownloading them mod multiple times to no avail and I have no idea how to add these enchantments myself. I'm completely stumped.

**Comment by Stereowalker** [comment]
Enable stamina on your side

**Comment by Stereowalker** [comment]
And restart your game

**Comment by Hozq** [comment]
The thing is that we have stamina off in our config for the server so I don't see why it would have to be enabled. Going to try anyways

**Comment by Hozq** [comment]
Okay it worked but why do we have to have stamina turned on for us even though its disabled on the server is my only question

**Comment by Stereowalker** [comment]
If you want to run the server with stamina turned off, you're going to need to mess with the registry of the server and delete those two enchantments from it. In order to prevent the server from adding it in the first place, stamina needs to be disabled before you generate the world on the server

**Comment by Hozq** [comment]
Ahhhhhh Okay yeah that makes sense! Yeah our server was generated way before we added this mod. Thanks for the info
