### ISSUE TITLE
Feature Request: Temperature Gamerule

### ISSUE THREAD

**Issue by Riphtix** [Stereowalker/Survive#218]
Gamerule to turn on or off temperature. (ie /gamerule dotemperature [true|false])

**Comment by Stereowalker** [comment]
I don't see what the point of the gamerule is, You can already disable the module with the config

**Comment by Riphtix** [comment]
I ran into a lot of problems trying to disable it from the config on a personal server after I had been playing on the server for about a week. The game wouldn't let me load back in, my theory is that it has something to do with mismatching player data. However a gamerule would allow for the temperature system to be toggled from inside the game without needing to restart the server or causing this mismatch of player data. See report #219 that I posted for more info on the problem I was having. I ended up just creating a couple command blocks to infintely apply heat and cold resist.

**Comment by Stereowalker** [comment]
Oh, if that's the case, you would need to disable it on your client and restart your game

**Comment by Stereowalker** [comment]
Certain enchantments are unable to register whenever temperature is disabled which causes the registry mismatch

**Comment by Riphtix** [comment]
I understand, I guess it's really cumbersome to fix but requiring a bunch of people trying to play on a server to go into their configs and find the file for this just to turn off temperature is also not an easy feat. If it could be done through a gamerule it would be way easier to toggle the temperature for a large group of people, which would include people who are not well practiced with going into config files and changing things.

**Comment by Stereowalker** [comment]
Rather than a straight up fix, I believe a warning just needs to be given to those messing with the configs. I'm sure they just flipped the switch and hoped that the server would just let them connect

**Comment by Stereowalker** [comment]
If you're playing on any version lower than 1.18.2, there is no chance of seeing that warning though, so you're on your own to warn potential visitors to restart their game
