### ISSUE TITLE
Mixin Transformer Error crash

### ISSUE THREAD

**Issue by Catomax262** [Stereowalker/Survive#226]
report: https://mclo.gs/yKLUGlK

**Comment by Stereowalker** [comment]
You have tough as nails installed. Both mods don't work well together

**Comment by Catomax262** [comment]
How can i make it so there only are the sleep and stamina modules? I can't seem to get these.

**Comment by Stereowalker** [comment]
I'm currently unaware of how to certain mixins from working if certain modules are disabled. Even if I did, I doubt I'd implement it on 1.16.5
