### ISSUE TITLE
Thirst Potion Effect Config Option

### ISSUE THREAD

**Issue by Lonemind** [Stereowalker/Survive#230]
Would it be possible to add a config option to change the severity of the thirst potion effect? As it is I simply ignore the effect since it doesn't provide any real consequences. There's no real reason to purify water at all. I personally feel that if you drink unpurified water you should have a net loss of thirst instead of a net gain. Others may disagree of course.

**Comment by Insane96** [comment]
I think Thirst is based off hunger, which has no real consequences too.

**Comment by Lonemind** [comment]
Which is why I use your IguanaTweaks mod to make hunger matter. I'd like to be able to do something similar with Survives Thirst mechanic.

**Comment by Stereowalker** [comment]
@Lonemind and @Insane96, The thirst potion effect by itself is inconsequential. If both well-being and thirst are enabled, drinking unclean water 3 times will trigger a random unwell debuff after 2-5 minutes which lasts 5 minutes and cannot be removed via conventional means. I would think it rather dull if I raised how severe the effect is as it would cheapen the survival experience. 7.0.4 patches a bug relating to this, so I hope you enjoy the fruits of my labor

**Comment by Insane96** [comment]
> trigger a random unwell debuff after 2-5 minutes which lasts 5 minutes and cannot be removed via conventional means

This helps the cause
