### ISSUE TITLE
origins and your mod doesnt work

### ISSUE THREAD

**Issue by butterflygirl30** [Stereowalker/Survive#235]
im playing 1.16.5 origins and your mod dont mix i got this error:
[crash-2022-06-28_13.53.30-fml.txt](https://github.com/Stereowalker/Survive/files/9003932/crash-2022-06-28_13.53.30-fml.txt)

**Comment by Stereowalker** [comment]
I'm closing this issue because it seems you're using a completely custom Origins build. Origins doesn't have a 1.0.0 version in 1.16.5 and thus I have no way of recreating this issue whatsoever. Use the latest 1.16.5 version of origins or update your build from it's GitHub page
