### ISSUE TITLE
Crash at loading "Not Enough Data"

### ISSUE THREAD

**Issue by Pandaw15** [Stereowalker/Survive#237]
Hi, so I first came across this issue in 7.0.3, so I decided to update Survive and UnionLib; however the crash persists

Here's the log: https://pastebin.com/LKV4Sayh

The error seem to be "Survive (survive) has failed to load correctly [...] com.electronwill.nightconfig.core.io.ParsingException: Not enough data available"

**Comment by Stereowalker** [comment]
I believe you should reset your configs to address the issue, that is if you've already modified your config files

**Comment by Pandaw15** [comment]
It worked, for some reasons a few mods needed to reset the configs even tho we haven't updated them or anything. Anyway, thx !
