### ISSUE TITLE
[Suggestion] FE powered heat pump for late game

### ISSUE THREAD

**Issue by enimog** [Stereowalker/Survive#238]
Hello there :)

I've played with survive for a while, and I really like the concept. But when combined with serene season, the temperature management get to be a pain quickly. You are very often toggling between cooling and heating inside your own base. You can technically automate that process with a season sensor I know... but anyway.

So I was thinking that for modpacks it would be interesting to have some sort of heat pump for your base; A block that is powered by FE, and will either cool or heat a specific area depending on what is needed, just like it work in real life. I remember having used an addon for tough and nails that did just that a long time ago.

**Comment by Stereowalker** [comment]
I've given your idea some thought over the past few days, and sadly it's not something I can implement. Although the idea is nice and all, the reason why the temperature regulator exists in the form that it does right now is that Block Entities cannot be moved via pistons. Sure, you could install mods to circumvent this limitation via other mods, but I don't want to make something that completely depends on other mods for functionality. I'll consider converting the Temperature Regulator when a parity introduces moving BEs to Java
