### ISSUE TITLE
Gaining the Fire Resistance effect and pressing [Esc] (saving the game) crashes Minecraft

### ISSUE THREAD

**Issue by JNCHGTR** [Stereowalker/Survive#248]
Gaining the Fire Resistance effect and pressing [Esc] (saving the game) crashes Minecraft

Here's my crash report: https://gist.github.com/JNCHGTR/88372324fe77c7300aba399ff081f313

Here's the latest.log: https://gist.github.com/JNCHGTR/ae346b8bf6c046f6bc2ec1e89a75a2d6

Steps to re-create: Eat an Enchanted Golden Apple (or give yourself Fire Resistance any other way), press [Esc] or wait for the game to save by itself

Minecraft 1.16.5 / Forge 36.2.39 / Mod version 1.16.5-3.4.7 

Currently just running OnionLib + Survive

**Comment by JNCHGTR** [comment]
Is there any progress on this?

**Comment by Stereowalker** [comment]
This has been a real pain to fix. What's causing the issue most likely is the heat resistance attribute not registering correctly and I haven't been able to replicate the bug. What I've done is to prevent the fire resistance effect from giving you heat resistance if the attribute isn't registered and as a result, you won't get the heat resistance if this error occurs. If it crashes again, feel free to reopen this issue whilst providing a crash report and your latest log

**Comment by JNCHGTR** [comment]
Hey Stereo,

First off - Thanks for looking into this.

Sadly I have to report that the issue is still happening. I just tried on my modpack with all of the other mods I use + by itself with UnionLib. Here are my findings:

**Tested in the modpack:**
latest.log - https://gist.github.com/JNCHGTR/03e1053b1c97b09201600c3e872ed045
crash report - https://gist.github.com/JNCHGTR/f619bf1615f6fc36dedb2ad022900c11

**Tested in a new instance with just Survive + UnionLib:**
latest.log - https://gist.github.com/JNCHGTR/239f6e88fb71da537ecfb53603493a15
crash report - https://gist.github.com/JNCHGTR/95c8f5ade8e037e37944c6fde06aace4

**NOTE: I found something very interesting. The crash only seems to happen AFTER I disabled the mod's stamina system in the in-game config. I also disabled the temperature system but it didn't crash from just that. It only crashed after I disabled stamina + temp. Not 100% sure if you need to disable both to replicate the issue or if it's just stamina but I'm sure this will help you replicate it.**

**Comment by JNCHGTR** [comment]
> This has been a real pain to fix. What's causing the issue most likely is the heat resistance attribute not registering correctly and I haven't been able to replicate the bug. What I've done is to prevent the fire resistance effect from giving you heat resistance if the attribute isn't registered and as a result, you won't get the heat resistance if this error occurs. If it crashes again, feel free to reopen this issue whilst providing a crash report and your latest log

Also, sorry! I can't seem to re-open the issue. Could you help me with that?
