### ISSUE TITLE
Will you make a 1.19 version?

### ISSUE THREAD

**Issue by LTGaming2009** [Stereowalker/Survive#251]
Hey there, ive seen your mod and really want to put it on my minecraft server but the server is 1.19 only and i really like the mod so i ask you, will you make a 1.19 version of the mod please? it looks great and for a server like mine it could really boost the realistic/mystical feel of servers like mine. all i ask is can you make a 1.19 version of it, thanks.

**Comment by Stereowalker** [comment]
I intend to as soon as all the bugs on the 1.18.2 branch are fixed

**Comment by Stereowalker** [comment]
And I also want to make it feasible to create a fabric version of the mod
