### ISSUE TITLE
Does not work on the 1.18.2forge server

### ISSUE THREAD

**Issue by 1233Ao** [Stereowalker/Survive#252]
server：
forge-1.18.2-40.1.73
mod：
Survive-1.18.2-7.1.0
UnionLib-1.18.2-7.2.0-Forge
The UnionLib can run, but the server crashes when it installs Survive
[debug.log](https://github.com/Stereowalker/Survive/files/9429042/debug.log)
[latest.log](https://github.com/Stereowalker/Survive/files/9429043/latest.log)
The following is the console build
[新建 文本文档.txt](https://github.com/Stereowalker/Survive/files/9429048/default.txt)
I use Microsoft Translator and may have some syntax errors

**Comment by Stereowalker** [comment]
Should be fixed now
