### ISSUE TITLE
Config Suggestion: Able to use Temperature gui but no Hypothermia or Hyperthermia 

### ISSUE THREAD

**Issue by Figgmastah** [Stereowalker/Survive#255]
I very much like the immersion you get off the hud changing color based on the temperature, only thing is Hypothermia and Hyperthermia dont quite fit into the modpack. Is there any way that you could make a option to disable Hypothermia and Hyperthermia but still keep the hud element?

![2022-09-11_00 23 03](https://user-images.githubusercontent.com/76262849/189503989-443a4258-3518-461a-93b1-928e92e05f3d.png)

**Comment by Stereowalker** [comment]
Disable the wellness module. It causes Hyperthermia and Hypothermia. I'll add a config option in the wellness module to disable this specific feature in an update

**Comment by Figgmastah** [comment]
Wellness module? What is that?

**Comment by Sember225** [comment]
Most likely the "wellbeing-common.toml" Config file. Thanks Stereo!

**Comment by Figgmastah** [comment]
I can't find any "wellbeing-common.toml". I have checked config, defaultconfigs and serverconfigs. 

Could you tell me where you found it?

**Comment by Sember225** [comment]
config > survive configs > wellbeing-common
