### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Developer2704** [Stereowalker/Survive#257]
Can you add an ability to add armor weight and tempature to modded armors in the config

**Comment by Stereowalker** [comment]
I'm not reverting to configs for that. The reason I moved away from configs is that they hinder updates to the mod. If I decide on a whim to change the weight of diamond armor to be heavier right now, that change will not be perceived by anyone updating the mod. It would require one to reset their config for that change to be seen by everyone updating the mod

**Comment by Stereowalker** [comment]
I like configs as much as the next person, but changes like those to the mod would require that I forcefully reset config values for everyone updating the mod and I'm tired of doing that

**Comment by Developer2704** [comment]
there is no tutorial on how to make an armor datapack. Can you make a wiki or datapack tutorial?

**Comment by Developer2704** [comment]
can you make a wiki or datapack

**Comment by Stereowalker** [comment]
For now join the discord server I have working examples there

**Comment by Developer2704** [comment]
can you make a wiki. 
i dont want to deal with discord

**Comment by Stereowalker** [comment]
It's been 23 days and I'm proud and a bit tired to announce my latest finished product, my [homepage](https://stereowalker.github.io/My-Home-Page). You can look through it whilst working on your datapack tutorial
