### ISSUE TITLE
Can't drink water from water sources

### ISSUE THREAD

**Issue by Proxwian** [Stereowalker/Survive#258]
On dedicated server (1.18.2) after restart players can't drink water from water sources even server config was not changed. I can't say what it depends on, but most times players can't drink water after restart, sometimes they can

**Comment by Proxwian** [comment]
P.S. I know, that drink works with SHIFT-Right Click

**Comment by Stereowalker** [comment]
Let me run some tests

**Comment by Proxwian** [comment]
It looks like config works only first time server started after i made changes.
Fields "Boolean: Drink From Flowing Water" and "Boolean: Remove Source Water Block"
