### ISSUE TITLE
suggestion: compat with pam's harvestcraft drinks/ sanity system?

### ISSUE THREAD

**Issue by kuroyure** [Stereowalker/Survive#26]
the first one is for convenience, the second is a thing that other similar mods did, harmfull gases in caves/crumbling because if mining could also be interesting concepts, i love survivalism mods, keep up the good work, i have great hopes for this mod

**Comment by znaxcy** [comment]
You can update the config to include to include at least the items from those mods. For example, in the config where:
`"Water Containers (Heated)" = ["minecraft:rabbit_stew,1"]`
you could add the following items:
`"pamhc2foodcore:hotchocolateitem,1", "pamhc2foodcore:hotteaitem,1", "pamhc2foodcore:hotcoffeeitem,1", "pamhc2foodcore:stewitem,1", "pamhc2foodcore:potatosoupitem,1", "pamhc2foodcore:carrotsoupitem,1", "pamhc2foodcore:pumpkinsoupitem,1", "minecraft:mushroom_stew,1", "pamhc2foodcore:noodlesoupitem,1"`
such that it reads:
`"Water Containers (Heated)" = ["minecraft:rabbit_stew,1", "pamhc2foodcore:hotchocolateitem,1", "pamhc2foodcore:hotteaitem,1", "pamhc2foodcore:hotcoffeeitem,1", "pamhc2foodcore:stewitem,1", "pamhc2foodcore:potatosoupitem,1", "pamhc2foodcore:carrotsoupitem,1", "pamhc2foodcore:pumpkinsoupitem,1", "minecraft:mushroom_stew,1", "pamhc2foodcore:noodlesoupitem,1"]`
This should enable the listed items to each replenish 1 thirst with the heated effect. The other areas in the config relevant to chilled effect, no effect or thirst effect can be updated similarly.

**Comment by znaxcy** [comment]
I just went ahead and wrote all of foodcore and the current foodextended in 1.15.2 for you, as I needed it anyway.
```
[thirst]
	#Disabling this will disable this mods thirst system
	"Enable Thirst" = true
	#This list defines which items replenish thirst when consumed
	#Items in this list will give the chilled effect upon drunk
	#Example: "minecraft:beetroot_soup,1"
	"Water Containers (Chilled)" = ["minecraft:beetroot_soup,1", "pamhc2foodcore:applesmoothieitem,1", "pamhc2foodcore:sweetberrysmoothieitem,1", "pamhc2foodcore:melonsmoothieitem,1", "pamhc2foodextended:cherrysodaitem,1", "pamhc2foodextended:colasodaitem,1", "pamhc2foodextended:energydrinkitem,1", "pamhc2foodextended:gingersodaitem,1", "pamhc2foodextended:grapefruitsodaitem,1", "pamhc2foodextended:grapesodaitem,1", "pamhc2foodextended:lemonlimesodaitem,1", "pamhc2foodextended:orangesodaitem,1", "pamhc2foodextended:rootbeerfloatitem,1", "pamhc2foodextended:rootbeersodaitem,1", "pamhc2foodextended:strawberrysodaitem,1", ]

	#This list defines which items replenish thirst when consumed
	#Items in this list will not give any extra effects
	#Example: "minecraft:mushroom_stew,1"
	"Water Containers" = ["minecraft:potion,1", "betteranimalsplus:goatmilk,1", "pamhc2foodcore:cookiesandmilkitem,1", "pamhc2foodcore:melonjuiceitem,1", "pamhc2foodcore:sweetberryjuiceitem,1", "pamhc2foodcore:p8juiceitem,1", "pamhc2foodcore:applejuiceitem,1", "pamhc2foodcore:freshwateritem,1", "pamhc2foodcore:freshmilkitem,1", "pamhc2foodcore:fruitpunchitem,1"]
	#This list defines which items replenish thirst when consumed
	#Items in this list will give the heated effect when drunk
	#Example: "minecraft:rabbit_stew,1"

	"Water Containers (Heated)" = ["minecraft:rabbit_stew,1", "pamhc2foodcore:hotchocolateitem,1", "pamhc2foodcore:hotteaitem,1", "pamhc2foodcore:hotcoffeeitem,1", "pamhc2foodcore:stewitem,1", "pamhc2foodcore:potatosoupitem,1", "pamhc2foodcore:carrotsoupitem,1", "pamhc2foodcore:pumpkinsoupitem,1", "minecraft:mushroom_stew,1", "pamhc2foodcore:noodlesoupitem,1"]

	#This list defines which items replenish thirst when consumed
	#Items in this list will randomly give the thirst effect when drunk
	#Example: "minecraft:honey_bottle,1"
	"Water Containers (Thirst)" = ["minecraft:honey_bottle,1"]


```

**Comment by Stereowalker** [comment]
It's been 3 months since your comment, I'd like to inform you that the config no longer supported and we now use datapacks. If you're in our discord server, check the #datapacks channel for a Pam's Harvestcraft datapack submitted there. If you're not in the server, https://discord.gg/8MXShqa
