### ISSUE TITLE
[Question + Issue] Can the Stomachache system be disabled and most food causing stomachache

### ISSUE THREAD

**Issue by Catomax262** [Stereowalker/Survive#264]
Is it related with nutrition? If it is i didn't have nutrition enabled and it still granted the effect.

**Comment by zalfrost** [comment]
I don't know what option enabled it but I can tell you that the stomachache only appears if you overeat/overdrink when your hunger bar/thirst bar is full. So make sure that you stop eating food that gives you a lot of food points when your hunger bar loses 1 or 2 points of hunger. It's not an issue.

**Comment by Stereowalker** [comment]
To think I'd find someone who would find the point of the feature. Puts a tear in my eye 🥲.

If you want to disable the feature, you can do so in the server config. Just know that if your character has already eaten past the max, the debuffs will not go away, you'll have to work out the extra from your system.

Thanks for the smile, see you in another issue
