### ISSUE TITLE
[Crash] 8ii strikes again

### ISSUE THREAD

**Issue by Catomax262** [Stereowalker/Survive#267]
This is driving me crazy. You can no longer enter cold biomes like frozen oceans.
log: https://mclo.gs/Vd7m1Gc

**Comment by K4N0** [comment]
Wow, this is the mod that's been causing my Server to crash over and over again for the 8ii issue?

**Comment by Catomax262** [comment]
It is, unfortunately Stereowalker apparently doesn't check these very often,

**Comment by MissSweetViolet** [comment]
Having this too, I hope it's checked soon, cause this is in my opinion the best survival mod out there, and I've tried out many.

**Comment by Toma400** [comment]
Same happens with Serene Seasons for me, I guess this is because Serene Seasons' winter makes biomes change properties?
Log from me:
[latest.log](https://github.com/Stereowalker/Survive/files/10197619/latest.log)

(1.18.2, Forge, Survive 7.1.3)

**Comment by joe-vettek** [comment]
it's the same with me!!! I'm a little nervous

**Comment by Stereowalker** [comment]
Fixed
