### ISSUE TITLE
Crashing when near cold block

### ISSUE THREAD

**Issue by zZParabellumZz** [Stereowalker/Survive#269]
game is crashing when i get near a cold block(i also have serene seasons installed and snow! real magic). Game version 1.18.2. Here's the crash log:
[crash-2022-12-21_19.49.00-server.txt](https://github.com/Stereowalker/Survive/files/10282270/crash-2022-12-21_19.49.00-server.txt)

**Comment by Stereowalker** [comment]
Took a look at your crash log. You're using 7.1.3 and the 8ii bug has been fixed in a newer version. Upgrade to that and if you're having any issues with it, feel free to create another issue

**Comment by zZParabellumZz** [comment]
Thanks for letting me know :)
