### ISSUE TITLE
Should thirst and stamina work in peaceful?

### ISSUE THREAD

**Issue by APrimevalWorld** [Stereowalker/Survive#271]
Just a genuine question, because I suspect I'm experiencing a bug but I'm not entirely sure. I'm on Peaceful, got the stamina + thirst bars to appear after doing some configuring ingame to the RPG HUD mod, and I am getting a tiredness debuff... but my bars aren't going down. I'm usually a Tough As Nails user, so I've never actually used this mod before and I could be completely misinterpreting this. I just, don't really understand it.

In case this is a bug, I suspect it's an error with a HUD mod like RPG HUD or The One Probe - both of which I am using. I will be doing some tests to see if I can fix this regardless, or at least find a work around.

**Comment by Stereowalker** [comment]
You could say it's a bug. Thirst and Stamina both have safeguards in peaceful like hunger does. The sleep mechanic lacks any peaceful safeguards
