### ISSUE TITLE
[BUG] Issue when joning server with the survive mod - player instantly gets disconencted on world join

### ISSUE THREAD

**Issue by greencreeper12** [Stereowalker/Survive#272]
I have an aternos server im running, I installed the survive mod and the unionlib mod
Whenever anyone tries to join the server it instantly kicks the player
So far Ive ruled out a few possibilitys
Internet - The wifi is perfectly fine and i can join other servers without mods
Personal side issue - I had a friend help me test out the server and they cant join either
Version issue - all of our mods are on the lastest game version, on forge 44.1.0, and using the same mod versions

Please help

![image](https://user-images.githubusercontent.com/122134505/219537910-1f0163ee-11b2-4963-b189-2392ca354a5e.png)
![image](https://user-images.githubusercontent.com/122134505/219537955-ea36ce75-b480-4b55-9bb7-66f7d904e142.png)
https://mclo.gs/wglKxVl

**Comment by Stereowalker** [comment]
I'll see what I can do to fix the issue

**Comment by Stereowalker** [comment]
I've fixed the bug, you should be able to connect to your server now
