### ISSUE TITLE
Is a version 1.19.2 planned?

### ISSUE THREAD

**Issue by Lenoxiduds** [Stereowalker/Survive#276]
Hi, I wanted to know if a 1.19.2 version was planned? This is the only mod I'm missing in this version and I'm obviously not the only one waiting for a 1.19.2 version. That would be really cool. Anyway thanks for your work, your mod is really great and very well thought out. That's why I miss it so much!

**Comment by Stereowalker** [comment]
I'll be frank, I'm not really sure if I do want to make a 1.19.2 version, but the biggest burden for me will be maintaining it.

**Comment by Lenoxiduds** [comment]
Oh I see... :/ I don't realize how much work it takes to port to 1.19.2. Anyway I hope you'll release it, I miss your mod a lot! 
But if it's really too complicated, I understand. Anyway, thanks for your answer and all the best!

**Comment by Stereowalker** [comment]
Complicated isn't the issue, it's maintainability. It's the very reason why a fabric port of this mod doesn't exist yet. Just keep an eye out for a 1.19.2 port of the UnionLib mod for Forge. That essentially means I've cleared the most difficult hurdle

**Comment by Lenoxiduds** [comment]
Ah yes I understand what you mean. Sorry I'm French, I had misunderstood the meaning of "maintainability". Indeed, I imagine that it must be a lot of work... I'll just have to pray very hard then haha! 

The main thing is that you enjoy doing it. Anyway, thanks for answering me, it's very nice. Whatever you do, I wish you good luck and thank you for the work you do, it's really a great job!

**Comment by Cookizza** [comment]
Firstly thanks for this great mod!

1.19.2 is the most popular version for modpack creators on 1.19.x currently. i would argue it would be more beneficial to maintain a 1.19.2 over a 1.19.3 version of the mod.

If there are specific challenges in going from 19.3 to 19.2 I'd love to get involved to help!

**Comment by Stereowalker** [comment]
The only challenge involved is porting back and forth between 1.19.2, 1.19.3 and now 1.19.4. If I were porting the mod once, it wouldn't be a problem. The big issue is I have to do this every single time I update Survive or Tiered
