### ISSUE TITLE
[BUG] on my server none of my players seems to be able to drink water from a block

### ISSUE THREAD

**Issue by greencreeper12** [Stereowalker/Survive#279]
So I have this server set up, and have a few friends who play on it
I can drink water from a block of water source block perfectly fine and yet none of my friends seems to be able to do so
When I tell them to shift and right click it dosnt do anything and I dont understand why am I the only person who **_dosnt_** have this issue
I did enable the config where when you drink from a water block it removes it, and Im the only person with op, 
Is the config or op messing with drinking somehow?
Please help me fix this issue
[thirst-common.txt](https://github.com/Stereowalker/Survive/files/10947637/thirst-common.txt)
^The thirst config file text

**Comment by Stereowalker** [comment]
This is the config for the server right?

**Comment by greencreeper12** [comment]
yes, i downloaded the config file and changed it to a txt file so it can be uploaded into github
uploaded because just in case it was the cause

**Comment by Stereowalker** [comment]
Thank you for bringing this bug to my attention. I've replicated and will patch this in a future release
