### ISSUE TITLE
[Question] How to disable Stomachache debuff?

### ISSUE THREAD

**Issue by Catomax262** [Stereowalker/Survive#281]
I honestly despise it. When i'm low on health i can't use big foods to heal myself because of this stupid debuff. Basically, all huge saturation foods are completely useless because of this.

**Comment by Stereowalker** [comment]
You can disable it in the server configuration file

**Comment by Catomax262** [comment]
> You can disable it in the server configuration file

I can't find anything related to this in the config file. Did you even put that?

**Comment by Catomax262** [comment]
Also, i checked "Expanded Stomach Capacity" to false, and it changed nothing.

**Comment by LeKripiY** [comment]
Hello, any solution to this problem ? I searched for ways to disable this but i didn't find anything, this issue is still relevant, so please get us a fix to this.

**Comment by Stereowalker** [comment]
It's in your server config. `world_folder/serverconfig/survive-server.toml`

**Comment by LeKripiY** [comment]
![image](https://github.com/Stereowalker/Survive/assets/77859121/b2fb426d-4574-408a-8439-001a5f4c8ef6)
 This should work ?

**Comment by Stereowalker** [comment]
Yes, It disables the feature

**Comment by LeKripiY** [comment]
it worked, thank you !

**Comment by Catomax262** [comment]
> Yes, It disables the feature

for some reason it still gives me stomachache regardless of if it's true or false

**Comment by jacobturpen** [comment]
> > Yes, It disables the feature
> 
> for some reason it still gives me stomachache regardless of if it's true or false

I noticed I still had stomachache after I disabled it too. If you die, it takes it away, and you can't get the debuff again

**Comment by doarlock** [comment]
You must change  "Expanded Stomach Capacity" feature to false. Can be located on "config/survive-server.toml", and once you changed it, copy the file to next folder "defaultconfigs", this will let you create servers/singleplayer worlds with this feature disabled by default

**Comment by Stereowalker** [comment]
> You must change  "Expanded Stomach Capacity" feature to false. Can be located on "config/survive-server.toml", and once you changed it, copy the file to next folder "defaultconfigs", this will let you create servers/singleplayer worlds with this feature disabled by default

This
