### ISSUE TITLE
(1.19.2) Server Disconnect when joining world

### ISSUE THREAD

**Issue by uchikun** [Stereowalker/Survive#283]
I have a heavily modded forge LAN server that will startup fine with the mod but when I try to join the world it disconnects and gives me an error. If I remove the mod I can join just fine. I am not sure if its a compatibility issue.

Please forgive if I am submitting wrong this is my first time submitting an error!

https://gyazo.com/3bb273d4de62c0e61a59b610c0afe598
https://gyazo.com/fd3835c8ab92deb74b9324382b32a9d3

**Comment by Stereowalker** [comment]
Worry not, I can say for sure that this isn't a compatibility issue

**Comment by uchikun** [comment]
> Worry not, I can say for sure that this isn't a compatibility issue

https://pastebin.com/QUjwhzbF

i was able to playtest with no other mods but unionlib and survive on a forge server (43.2.10) on version (1.19.2) and i figured out how to post the full log,i hope this helps, i appreciate the response ;; i really love your mod!! but I cant seem to use it

**Comment by Stereowalker** [comment]
Fixed in 8.0.8.2
