### ISSUE TITLE
Game exits with new 1.19.2 backport

### ISSUE THREAD

**Issue by Pandaw15** [Stereowalker/Survive#284]
Hi, I just added the 1.19.2 backport to my modpack (forge 43.2.8) and the game just doesn't launch; the log stops with Survive related stuff.
The related log part: https://pastebin.com/b4Huw4iV
The full log just in case (there's no crash report): https://pastebin.com/ed3VV90f

I don't know if it's a compatibility issue, could be, given the end of the log.

**Comment by Stereowalker** [comment]
It's a conflict with dungeon library

**Comment by Stereowalker** [comment]
My mod (UnionLib) modifies the bow class to make the draw speed configurable via attributes. If Dungeon Library does the same thing, then there's no resolving the conflict

**Comment by Pandaw15** [comment]
Oh I see. Isn't it something that could be configurable ? Like "drawspeed configurable = true/false"
Or maybe the configs are not read yet at this time of the loading process.

**Comment by Stereowalker** [comment]
Unfortunately not. It's a mixin thing

**Comment by Pandaw15** [comment]
Alright, thanks anyway!
