### ISSUE TITLE
[Suggestion] Make items in inventory / held able to modify player's temperature

### ISSUE THREAD

**Issue by Kevadroz** [Stereowalker/Survive#288]
For example having a torch should give you some heat.
Maybe implement it as a new data path like `[modid]/survive_modifiers/items/[itemid]` with a similar format as armors?

**Comment by Stereowalker** [comment]
As nice as the idea might seem, it's not something I can add to 1.19

**Comment by Stereowalker** [comment]
Also, congratulations on delaying the 1.20 release even further

**Comment by Kevadroz** [comment]
They say a delayed product is better than a rushed one, so I see this as a win.

**Comment by Stereowalker** [comment]
For now, only torches have the ability to modify your temp. I'm temporarily using the temp value for the torch block
