### ISSUE TITLE
[Bug] 1.20.1 Items do not stack correctly when picked up.

### ISSUE THREAD

**Issue by HistoriaGamer** [Stereowalker/Survive#293]
This could be a bug or an incompatibility of some kind, but discovered that the mod is making item collection erroneous. Items when picked up do not auto stack in inventory and use up one slot at a time and have to be forced back into stacking.

**Comment by Stereowalker** [comment]
It was due to me adding food spoilage. I've fixed the issue and have allowed food items crafted in one minute intervals to be stackable if food spoilage is enabled
