### ISSUE TITLE
UnionLIB crash

### ISSUE THREAD

**Issue by BiakCeu** [Stereowalker/Survive#296]
I have the lastest version of Survive and UnionLIB. But the crash states I need the latest version of lib despite me having it. I lowered the version of UnionLIB which fixed it but now the mod Tiered, also by you, requires the latest. Now I'm in a pickle since I would like to play with both mods.
https://pastebin.com/292gfVwX
There's the log. No crash report since it won't generate for whatever reason.
---Here's the log for Tiered if you'd like.
https://pastebin.com/7k6ps6tJ

**Comment by Stereowalker** [comment]
Sorry for the trouble, Survive has been updated to work with the newest version of UnionLib. UnionLib is versioned the way it is to prevent anyone from using it when I explicitly break something and report it as an issue
