### ISSUE TITLE
Maybe I'm just dumb, but any and all combinations of the Forge Survive mod on 1.19.2 end up crashing, even with no other mods

### ISSUE THREAD

**Issue by troglodyte06** [Stereowalker/Survive#297]

**Comment by troglodyte06** [comment]
Running the 1.19.2 version and it says it needs a version of UnionLab that is not for 1.19.2?

**Comment by AceTheEldritchKing** [comment]
I am having the same issue too and the mod fails to load

**Comment by troglodyte06** [comment]
oh,
I am an idiot, 1.19.2-9.0.4.1-Forge.jar works

**Comment by delveticas** [comment]
close the issue dumbass
