### ISSUE TITLE
[Feature Request] Alterations to the thirst system

### ISSUE THREAD

**Issue by Darkosto** [Stereowalker/Survive#30]
Hello!

Would it be possible make a few additions to the configs for the thirst system?

1. When drinking from a source block it uses up the water (that way you can't keep drinking from the same place)
2. When you do drink from the 'ground' your debuff is much more detrimental (intensity configurable?) to incentivize players to filter their water? (Or maybe even allowing custom effects to be added in config? Like allowing potion effects to be added?)

Thanks for your awesome mod!

**Comment by Stereowalker** [comment]
Thanks.
Updates on your suggestions
1) I've applied this change to the mod
2) I cannot add this change because the way water could be placed by the player. It would just feel unfair to these players
