### ISSUE TITLE
[Bug with Survive forge 1.16.1]

### ISSUE THREAD

**Issue by Fireworkstars46** [Stereowalker/Survive#306]
So I have the survive mod on forge 1.16.1 and the mod is bugged and making the falling trees mod speed modifier setting not work and making it be normal speed when it's suppose to be slowed. Would it be possible for it to be fixed? I can't play my oneblock map until this mod gets fixed or someone can find me a new thirst mod to use or a datapack instead.

**Comment by Stereowalker** [comment]
This will take a while because I don't have the source code for 1.16.1 and I'm going to have to revert the 1.16.5 build

**Comment by Fireworkstars46** [comment]
When you get to it let me know ok?

**Comment by Stereowalker** [comment]
Seems completed. Create a new issue if further problems arise
