### ISSUE TITLE
Compatibility Issues 

### ISSUE THREAD

**Issue by MrFlamazing** [Stereowalker/Survive#311]
1.21.1 NeoForge 
This mod has not been compatible with anything that I put in the pack with the mod and its dependencies. It just crashes the game.

**Comment by Stereowalker** [comment]
That doesn't seem right. I've got this mod in a pack with up to a hundred mods and they all run fine. You'll need to upload your crash log so that I can identify what mod you're crashing with

**Comment by MrFlamazing** [comment]
[crash-2024-09-19_14.17.15-client.txt](https://github.com/user-attachments/files/17064153/crash-2024-09-19_14.17.15-client.txt)
 Here is the crash report, I have even tried one by one with mods and survive and it still crashes.

**Comment by Stereowalker** [comment]
It's not an incompatibly. It's an issue specific to you. Something is locking that config file, so you should try deleting it

**Comment by MrFlamazing** [comment]
Okay, thank you.
