### ISSUE TITLE
Version uploaded to modirinth and curseforge is a dev / sources version and this doesn't work

### ISSUE THREAD

**Issue by adamoni123** [Stereowalker/Survive#312]
Not much to put in description, it's what the title says

**Comment by Poopooracoocoo** [comment]
To be clear, they're referring to the Fabric versions: 
https://www.curseforge.com/minecraft/mc-mods/survive/files/5719686
https://modrinth.com/mod/survive/version/1.21.1-10.1.2-beta-Fabric

Here's a crash with Survive on a dedicated server running Fabric: https://mclo.gs/OYBFGyY

**Comment by adamoni123** [comment]
> To be clear, they're referring to the Fabric versions: https://www.curseforge.com/minecraft/mc-mods/survive/files/5719686 https://modrinth.com/mod/survive/version/1.21.1-10.1.2-beta-Fabric

Oh yeah so sorry I forgot to say that

**Comment by Stereowalker** [comment]
Thank you for pointing it out. I've uploaded an update on both CurseForge and Modrinth with the correct files for fabric
