### ISSUE TITLE
The bowl should not be filled with water

### ISSUE THREAD

**Issue by Chigurh972** [Stereowalker/Survive#316]
The mod version is the latest 9.0.5, the game version is 1.20.1, and when I right-click the bowl at the water source, the bowl is still empty. At the same time, I noticed that while I was loading water with my main hand, my deputy hand was moving.

**Comment by Stereowalker** [comment]
Deputy hand?

**Comment by Stereowalker** [comment]
I've fixed it in 9.0.6. Thank you for reporting the issue
