### ISSUE TITLE
Code Contributions & Licensing Question

### ISSUE THREAD

**Issue by Kowbell** [Stereowalker/Survive#32]
I'm curious if you support contributions/PRs to the mod codebase? I know the source isn't available in some public git repository, only a downloadable zip. I'm also a little confused because in this repository you have a GPL license, on CurseForge the mod is listed All Rights Reserved, and in the source zip there's no license at all.

**Comment by Stereowalker** [comment]
I'm still deciding on a license for my mods so it's gonna show the default licenses for those sites for now. As for the contributions/PRs, I'm not sure I can really maintain that as I'm not constantly online. If someone makes a PR, I might not see it in time. And if I do actually come online, I'd be busy spending the limited internet connection uploading mod files or looking at issues in the issues page to really look at the PRs and even if I do look at them, so much of the codebase might have changed to render the PRs useless as I'm always fiddling with the mod. So I'm at an impasse regarding uploading the code here until I get a stable internet connection to maintain it. But still thanks for the reminder regarding the licence

**Comment by Stereowalker** [comment]
Well, I've settled on the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0. Thanks for asking this question
