### ISSUE TITLE
Update Check fails

### ISSUE THREAD

**Issue by MattiBorchers** [Stereowalker/Survive#34]
When I try to start my Server I got the following error message.
Maybe you could add a "enable version check option" in the settings.

`[14Dez2020 11:57:17.181] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [survive] Starting version check at https://raw.githubusercontent.com/Stereowalker/Survive/master/update.json
[14Dez2020 11:57:17.187] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
java.io.FileNotFoundException: https://raw.githubusercontent.com/Stereowalker/Survive/master/update.json`

**Comment by Stereowalker** [comment]
I believe this is something that forge does on its own. I doubt I can do anything about it

**Comment by MattiBorchers** [comment]
Ok, it don't crash the server or something, but I tought you might want to know it.
