### ISSUE TITLE
Thirst system prevents filling Mystical Agriculture watering can (MC Version 1.16.x)

### ISSUE THREAD

**Issue by codewolf219** [Stereowalker/Survive#36]
With Mystical Agriculture installed, right-clicking water to fill a watering can does not fill the watering can.  Disabling thirst system does not correct the issue.

Survive v3.0.1
Mystical Agriculture v4.1.3

**Comment by Stereowalker** [comment]
Is this now fixed for you in the latest version?

**Comment by codewolf219** [comment]
This appears to be resolved now.  Thanks!
