### ISSUE TITLE
Crashing when loading on my server, log attached.

### ISSUE THREAD

**Issue by RomoE** [Stereowalker/Survive#37]
[crash-2020-12-19_22.30.54-fml.txt](https://github.com/Stereowalker/Survive/files/5720613/crash-2020-12-19_22.30.54-fml.txt)

**Comment by NotoriusQ** [comment]
I'm having a similar issue
[crash-2020-12-23_03.22.52-fml.txt](https://github.com/Stereowalker/Survive/files/5734062/crash-2020-12-23_03.22.52-fml.txt)

**Comment by FurryApocalypse** [comment]
same problem on the newest version (server wont start).
Single player starts up fine.

**Comment by Coraline77447** [comment]
Same thing is happening to me as well FurryApocalypse...

**Comment by Stereowalker** [comment]
I believe this is no longer an issue.
