### ISSUE TITLE
[Bug] [Mod Incompatibility] Survive interferes with SimpleAbsorption's Attributes

### ISSUE THREAD

**Issue by NotoriusQ** [Stereowalker/Survive#43]
Incompatibility with Simple Absorption and Spice of Life: Potato that's causing my game to crash when I load into a world after I make what are supposed to be successful config edits adding Simple Absorption max hearts for achieved food diversity thresholds in SoL:Potato.
[crash-2021-01-04_09.51.54-server.txt](https://github.com/Stereowalker/Survive/files/5765466/crash-2021-01-04_09.51.54-server.txt)
> tell them KnightMiner says they are registering their attributes to the player wrong most likely

Mod version and Forge version
Forge Latest ~ .29
Survive 3.0.7
Simple Absorption 1.2.0
SoL:Potato 1.0.5

**Comment by NotoriusQ** [comment]
> "My prediction is they register their attributes to the player by taking the default list from PlayerEntity and adding their own, meaning any other mod adding attributes is ignored."

They also said that you could check out Simple Absorption's code for the solution

https://github.com/KnightMiner/SimpleAbsorption/blob/1.16/src/main/java/knightminer/simpleabsorption/SimpleAbsorption.java#L77-L85

**Comment by Kevun1** [comment]
The direct issue is that when Survive, Simple Absorption, and SOL:Potato are installed, the call to `player.getAttribute()` with the `simple_absorption:absorption_max` attribute returns `null` for some reason. This only happens with Survive installed, and not the other two mods alone. 

See [Kevun1/Spice-of-Life-Potato-Edition#5](https://github.com/Kevun1/Spice-of-Life-Potato-Edition/issues/5)

**Comment by NotoriusQ** [comment]
Using Forge ~ .36 now
Updating Survive from 3.0.7 to 3.0.9 made it so that when I joined the server, I'd get this message, once for each entry in my SOL:P config - 
>  [Server thread/WARN] [solpotato/]: ERROR: player does not have attribute: simple_absorption:absorption_max
Which would mean that I wouldn't get extra absorption from my SOL:P config. 
This would only happen every so often however, and if I restarted the server and my client it usually went away and then the extra absorption would function normally.

After updating to 3.0.11, I get that same message every time I join now.

I really appreciate that the temperate mechanics are working!!

**Comment by NotoriusQ** [comment]
Onto Forge ~.37
Survive 3.1.0
UnionLib 3.2.2

No crashing, but I'm still getting those same error messages. If I have just UnionLib installed, I don't have this issue, so I'm pretty sure it's either Survive or SimpleAbsorption.

If I try to give myself an attribute by command, everything else works, but with SimpleAbsorption's, it tells me "player doesn't have that attribute"

**Comment by Stereowalker** [comment]
This should be fixed in version 3.1.1

**Comment by Stereowalker** [comment]
If its not, reopen this issue
