### ISSUE TITLE
[Issue] Temperature Mechanics not Triggering (1.16.4-3.0.7)

### ISSUE THREAD

**Issue by Wabbit0101** [Stereowalker/Survive#44]
Environments: Development IDE (Eclipse) and Standalone Single-player
Game mode: **HARD**
Forge: **forge-1.16.4-35.1.29**
**SereneSeasons-1.16.4-4.0.0.86-universal.jar**
**Survive-1.16.4-3.0.7.jar**
**UnionLib-1.16.4-3.1.2.jar**
AppleSkin-mc1.16.2-forge-1.0.14.jar
carrotslib-mc1.16.4-3.0b2.jar
jei-1.16.4-7.6.1.65.jar

So I must be missing something here...I cannot get the temperature to change predictably in the 3.0.7 version. I've tried standing right next to 4 blocks of lava sources (nothing). Tried standing inside of 5 blocks of blue-ice (nothing). Screenshots with temperature bar at top attached...Biome is plains or mountains. Checked config to make sure temperature is enabled (it is). Moving up to a higher altitude does seem to trigger sudden freezing (so I know the internal system is working). Ran with and without Serene Seasons-- made no difference.

![survive_screenshot_hot](https://user-images.githubusercontent.com/15458867/103781110-e1e5f480-5003-11eb-874e-58f46f2dd87f.png)
![survive_screenshot_ice](https://user-images.githubusercontent.com/15458867/103781118-e4e0e500-5003-11eb-8a77-1b413d06d348.png)
[config.zip](https://github.com/Stereowalker/Survive/files/5776365/config.zip)

**Comment by Stereowalker** [comment]
Resend your screenshots with the Temp Display Mode set to NUMBERS. The bar can tend to misbehave some of the time

**Comment by Wabbit0101** [comment]
Added..I also added a pic of the hypothermia which starts at just a change of -2 deg (C) in same area but at higher elevation (+30 blocks). I turned off F3 as it was very hard to see temp value with all the debug info but it's basically the same spots as shown above. HTH.

![survive_screenshot_hot_numgui](https://user-images.githubusercontent.com/15458867/103849388-86068480-5072-11eb-8d36-2ea4839ac325.png)
![survive_screenshot_ice_numgui](https://user-images.githubusercontent.com/15458867/103849393-899a0b80-5072-11eb-9f0b-87997282d9bc.png)
![survive_screenshot_hypo_numgui](https://user-images.githubusercontent.com/15458867/103849398-8c94fc00-5072-11eb-81b5-0ce2c0fff5b6.png)

**Comment by Stereowalker** [comment]
I'm not really sure what happened internally to cause this issue so I did a rework on how the modifiers affect the player. You should give it a shot and tell me what you think about it
