### ISSUE TITLE
Block temperature config not working

### ISSUE THREAD

**Issue by FurryApocalypse** [Stereowalker/Survive#49]
Hey there.
I just wanted to say in the latest update *(forge 35.1.28) blocks temperatures changed in configs dont works. Just no difference if i stay near, on the block, or go away. Configured block do not radiate with temperature.

**Comment by Stereowalker** [comment]
Update the mod to 3.0.11 and confirm if this issue has been addressed

**Comment by FurryApocalypse** [comment]
Okay so heres what i checked
i set blocks to + and - 100 temp
Blocks still ignore to radiate temp like in 1/2/3 squer area 
However for blocks that you can sink in like WATER or SNOW temps seems to be applied correctly. 
i tested it also with bedrock +100 and different types of ice for -100
It looks like onlty the block itself changes temperature. Flowing water  and water sources works fine.

**Comment by Stereowalker** [comment]
Temperature Modes
NORMAL: Gets the average temperature of blocks in a 5 block radius
BLEND: Gets the average temperature of blocks in a 5 block radius while taking into account the block the player is in, the distance between the current block and the target block and the temperature difference between those blocks

**Comment by FurryApocalypse** [comment]
I tried both with no succes sadly. Water indeed started to radiate yes but rest of blocks stays the same.

**Comment by FurryApocalypse** [comment]
I apologize for mistake.
I created several new worlds to check it for sure. Changing config dont work for current world so NORMAL mode is not working. In BLEND temperature get is directly from the block youre in.

**Comment by Stereowalker** [comment]
Fortunately, I've removed configs and have made it data driven
