### ISSUE TITLE
Crash when you leave the game in the Undergarden dimension(from the Undergarden Mod)

### ISSUE THREAD

**Issue by Maxi90909** [Stereowalker/Survive#51]
https://pastebin.com/gPVwGDmT
All I did was I left the game in the undergarden dimension because of a crash and now Each time I start up the world this Crash report shows up

**Comment by Maxi90909** [comment]
The crash report shows it is something with the survive mod and the Serene Season Mod. By the way these Mods are both on the newest version.

**Comment by Stereowalker** [comment]
Please confirm if this is still the case in 3.1.0
