### ISSUE TITLE
Crash with Serene Seasons

### ISSUE THREAD

**Issue by Maxi90909** [Stereowalker/Survive#52]
https://pastebin.com/07ndhBtw
I Can't join my World anymore. Each time it loads the world it crashes and shows this Crash report. Survive, UnionLib and Serene Seasons are all on the lastest Version

**Comment by Stereowalker** [comment]
Please confirm if this is still the case in 3.1.0

**Comment by Maxi90909** [comment]
https://pastebin.com/38veLucf
The new Update made it worse now it crashes on startup. I have updated UnionLib to the version UnionLib-1.16.5-3.2.1 and Survive to the vesion 3.1.0 . Maybe it is the minecraft version because I still play on 1.16.4 ,but mojang says version 1.16.5 is compatible with 1.16.4 or is it?

**Comment by Maxi90909** [comment]
It now crashes on startup 😐

**Comment by zndrmn** [comment]
I have the same problem as well.
Everything is on the latest version, UnionLib, Survive
My Minecraft Ver is 1.16.5 Forge
I don't think it's because of Serene Seasons Because I took UnionLib and Survive out and it works fine.
I get some sort of gui error on startup.

java.lang.NullPointerException: Rendering overlay

I could send the whole crash report if you need me to.

**Comment by Maxi90909** [comment]
Yeah mine says java.lang.NullPointerException: Rendering overlay as well and I am Sure that it is survive and UnionLib because thats the only mods I have updated today and since then it is crashing. Thank you zndrmn now I Know that not the minecraft version is the problem.

**Comment by Maxi90909** [comment]
Please Fix Stereowalker because I like this mod and don't want to remove it.

**Comment by zndrmn** [comment]
Yeah np I also went through my entire mod list and updated every mod that could've been updated so yeah. it started as soon as I updated UnionLib and Survive. I hope this gets fixed soon cause this is a really great mod, a lot bunch of mods have been adding support for survive as well. Super underrated.

**Comment by Stereowalker** [comment]
Check UnionLib 3.2.2

**Comment by zndrmn** [comment]
Alrighty, I downloaded and ran UnionLib 3.2.2 with survival on 1.16.5 and 1.16.4 and I can now load into the menu screen without any problems. 

Now when ever I join a previous world or create a fresh one I get this error / crash
java.lang.NoSuchFieldError: enable_temperature

I've deleted my configs for survival and it didn't change the outcome if that helps.
Also I can send you my crash logs if you need me to.

**Comment by Maxi90909** [comment]
https://pastebin.com/NdxbYAnz
Can Load Minecraft to the main Menu but can't join a World because then it crashes and shows this report
[latest.log](https://github.com/Stereowalker/Survive/files/5841078/latest.log)
The first one is the crash report and the second is my logs 
I don't know what the problem is now but the crash report says something with Serene Seasons and Survive combat temperatur

**Comment by Stereowalker** [comment]
Check Survive 3.1.1. I believe I've addressed the issue there. If it has been fixed, close this issue

**Comment by The-Arcanian** [comment]
I got this crash with Survive 3.1.1. https://gist.github.com/The-Arcanian/703a178f8a8e40f3ba30491eb4b37a3f

**Comment by zndrmn** [comment]
Have a similar problem. (Survive 3.1.1 and also UnionLib 3.2.3)
https://gist.github.com/zndrmn/72e3b0e7089967f16273549a46951fe6#file-crash-2021-01-21_22-27-20-server-txt

**Comment by The-Arcanian** [comment]
@zndrmn That is a different issue. https://github.com/Stereowalker/Survive/issues/53

**Comment by zndrmn** [comment]
Oh I didn't see that post, got it.

**Comment by Maxi90909** [comment]
https://pastebin.com/sum7tUP9
Why??? Can load to main menu but can't load the world :(

**Comment by The-Arcanian** [comment]
@Maxi90909 Same thing I told zndrmn.

**Comment by zndrmn** [comment]
@Maxi90909 "Go Down A version. CarrotLib doesn't support the latest version of Survive"
So I think that you can close this report.

**Comment by The-Arcanian** [comment]
No, he has it in the right place. He does not have CarrotLib.

**Comment by zndrmn** [comment]
Oooh

**Comment by The-Arcanian** [comment]
So this does not seem to be just a Survive & Serene Seasons problem I can load Survive-1.16.5-3.1.1 & SereneSeasons-1.16.4-4.0.0.86-universal without problem.

<details>
  <summary>Mod List</summary>
  
  ```
  forge-1.16.4-35.1.37-client.jar
  FarmersDelight-1.16.3-0.3.0.jar
  QuarkOddities-1.16.3.jar
  inventorysorter-1.16.1-18.1.0.jar
  swingthroughgrass-1.16.4-1.5.3.jar
  astralsorcery-1.16.4-1.13.9.jar
  jei-1.16.4-7.6.1.65.jar
  jeiintegration_1.16.4-6.1.1.11.jar
  curios-forge-1.16.4-4.0.3.3.jar
  tetra-1.16.4-3.5.3.jar
  create-mc1.16.3_v0.3e.jar
  totaldarkness-1.2-1.16.3.jar
  mgui-1.16.4-3.1.3.jar
  AutoRegLib-1.6-47.jar
  StorageDrawers-1.16.3-8.2.1.jar
  SereneSeasons-1.16.4-4.0.0.86-universal.jar
  ftb-gui-library-1604.1.1.26.jar
  InventoryHud_1.16.x.forge-3.1.4.jar
  tombstone-1.16-6.2.3.jar
  structurize-0.13.100-RELEASE-universal.jar
  minecolonies-0.13.480-BETA-universal.jar
  observerlib-1.16.4-1.5.1.jar
  moreoverlays-1.18.11-mc1.16.4.jar
  Hwyla-forge-1.10.11-B78_1.16.2.jar
  voyage-1.16.4-1.0.3.jar
  JustEnoughResources-1.16.3-0.12.0.100.jar
  forge-1.16.4-35.1.37-universal.jar
  Quark-r2.4-296.jar
  morered-1.16.4-2.0.1.2.jar
  WailaHarvestability-mc1.16.2-forge-1.1.13.jar
  tellme-forge-1.16.4-0.9.1.jar
  ```
  </details>

**Comment by Maxi90909** [comment]
And Why can’t I ?😐

**Comment by Maxi90909** [comment]
https://pastebin.com/ATieLnfT
Updated Survive to the newest version 3.1.2 and Forge to 1.16.5. I don't know why it is continuosly Crashing. I think it is Serene Seasons, prove me Wrong if so.

**Comment by The-Arcanian** [comment]
I have it working on MC 1.16.5 with Survive-1.16.5-3.1.2 & SereneSeasons-1.16.4-4.0.0.86-universal. So it must be some other mod that is interfering. Or maybe your player data got corrupted? Maybe first trying creating a new word to see if it is world-specific? Then removing all mods we do not have in common and see what happens?

<details>
  <summary>My mod List</summary>
  
  ```
  AkashicTome-1.4-14
  AppleSkin-mc1.16.2-forge-1.0.14
  astralsorcery-1.16.4-1.13.9
  AutoRegLib-1.6-47
  BetterAdvancements-1.16.3-0.1.0.102
  Botania-1.16.4-410
  bwncr-1.16.4-3.9.16
  ClientTweaks_1.16.3-5.2.0
  cloth-config-forge-4.1.3
  Clumps-6.0.0.13
  Corail-Recycler-NE-1.16.4-360
  CraftingTweaks_1.16.3-12.2.0
  create-mc1.16.3_v0.3e
  curios-forge-1.16.4-4.0.3.3
  DynamicSurroundings-1.16.4-4.0.3.5
  FarmersDelight-1.16.3-0.3.0
  FastFurnace-1.16.3-4.3.0
  FastLeafDecay-v25
  FastWorkbench-1.16.3-4.4.1
  flatbedrock-1.16.4-1.1.6
  ftb-gui-library-1604.1.1.26
  HarderBranchMining-1.16.2-2.61.0.12
  Hwyla-forge-1.10.11-B78_1.16.2
  InventoryEssentials_1.16.3-2.2.0
  InventoryHud_1.16.x.forge-3.1.4
  inventorysorter-1.16.1-18.1.0
  jei-1.16.4-7.6.1.65
  jeiintegration_1.16.4-6.1.1.11
  JustEnoughResources-1.16.3-0.12.0.100
  mgui-1.16.4-3.1.3
  minecolonies-0.13.581-ALPHA-universal
  moreoverlays-1.18.11-mc1.16.4
  morered-1.16.4-2.0.1.2
  observerlib-1.16.4-1.5.1
  Patchouli-1.16.4-48
  Placebo-1.16.3-4.3.3
  QuarkOddities-1.16.3
  Quark-r2.4-296
  SereneSeasons-1.16.4-4.0.0.86-universal
  StorageDrawers-1.16.3-8.2.1
  structurize-0.13.113-ALPHA-universal
  Survive-1.16.5-3.1.2
  swingthroughgrass-1.16.4-1.5.3
  tellme-forge-1.16.4-0.9.1
  tetra-1.16.4-3.5.3
  tombstone-1.16-6.2.3
  totaldarkness-1.2-1.16.3
  UnionLib-1.16.5-3.2.3
  voyage-1.16.4-1.0.3
  WailaHarvestability-mc1.16.2-forge-1.1.13
  ```
  </details>

**Comment by Maxi90909** [comment]
It is fixed since serene Season updated
