### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by vientopicante** [Stereowalker/Survive#53]
https://pastebin.com/AmsehxqP

i get this crash log everytime i create a world. every mod is up to current date, i tried removing some mods, even tried porting it to 1.16.5, but i always got to the "joining world" screen and then my game would crash.

**Comment by Mysteriaa** [comment]
I came here to report a similar issue as well.
https://pastebin.com/R7W6yEiF

**Comment by Maxi90909** [comment]
I know this issue there is no way that you can play unless you remove Survive and UnionLib

**Comment by Stereowalker** [comment]
Go Down A version. CarrotLib doesn't support the latest version of Survive

**Comment by Stereowalker** [comment]
Should no longer be an issue

**Comment by Maxi90909** [comment]
You are Right 👍
