### ISSUE TITLE
Pam's HarvestCraft connection

### ISSUE THREAD

**Issue by MoneyIgos** [Stereowalker/Survive#54]
Maybe you can create another mod to connect drinks on Pam's GarvestCraft with thirsty regeneration?

**Comment by Stereowalker** [comment]
Rather than that, you could wait for the thirst feature to become data-driven and then make a request to Pam's to include it in their mod

**Comment by Stereowalker** [comment]
The update is out. You should make this request to Pam as it can be added via a datapack
