### ISSUE TITLE
[Bug] Sprinting on a horse still consumes stamina

### ISSUE THREAD

**Issue by GoldenPot8o** [Stereowalker/Survive#55]
I am not sure what triggers this bug, but I got on a horse and it consumed stamina while I was on the horse and sprinting. It also did damage like low stamina does.

**Comment by Stereowalker** [comment]
Check 3.1.1

**Comment by Stereowalker** [comment]
is this still an issue?

**Comment by GoldenPot8o** [comment]
I haven’t run into it again, so I don’t believe so.
