### ISSUE TITLE
I want to contribute to my localized translation

### ISSUE THREAD

**Issue by AnLeRIP** [Stereowalker/Survive#57]
**This is a Vietnamese translation and I want to contribute to your Mod, so that Vietnamese players can easily access and use with the mod, Thank you.**

Current translation is for the latest version.
[vi_vn.txt](https://github.com/Stereowalker/Survive/files/5864278/vi_vn.txt)

Since I couldn't upload the ".json" file, I changed the file extension to ".txt", change it back to ".json" when downloading.
Thanks.

Sorry english my bad

**Comment by Stereowalker** [comment]
I'll add it to the update
