### ISSUE TITLE
3.1.3 Survive on Forge 35.1.37 1.16.4 multiplayer server drinks dont work. 

### ISSUE THREAD

**Issue by Oriansenshi** [Stereowalker/Survive#59]
I have reset the configs multiple times, and the things i have added to the drinks list for chilled and heated effects are not working. I saw in the update log that something about how drinks are processed changed and that modpacks from before the update may need to update. I have no idea what that means, i have generated fresh config files for multiple times, but the drinks i have added still do not do anything.

**Comment by Stereowalker** [comment]
You're no longer meant to use the config file. The mod uses datapacks to achieve this. The option was left there in the config so that everyone can copy over their changes in the config file to their datapacks

**Comment by Oriansenshi** [comment]
is there a datapack file that i can edit to introduce these features, or do i need to create a new datapack?

**Comment by Stereowalker** [comment]
If you want to add the steak item, in your data pack create a new file, minecraft/survive_drinks/steak.json, and paste this into it

{
  "thirst": 1,
  "hydration": 1.0,
  "thirstChance": 1.0,
  "isChilled": false,
  "isHeated": false,
  "isEnergizing": false
}

edit the values to your liking. This also works for modded items, (items_namespace)/survive_drinks/(items_id).json

**Comment by Oriansenshi** [comment]
Wait, let me make sure i understand this properly. You are saying that in order to utilize the entire drinks portion of the mod, i need to create individual files for each drink and item that I want to interact with this mod, including vanilla items? That feels like a complete and utter step backwards in utility from the previous version. I think i will just roll back to 3.1.1 and call it a day. thank you for your time.

**Comment by Stereowalker** [comment]
Mind you, vanilla items have already been included by default
