### ISSUE TITLE
Crash: Survive killed Inspirations

### ISSUE THREAD

**Issue by slard3** [Stereowalker/Survive#6]
Minecraft:1.15.2
Forge: 31.2.0
Survive-1.15.2-1.5.0

Inspirations 1.1.0 for 1.15.2
Mantle-1.15.2-1.5.15

The game crashes when loading up.

[Crash report](https://gist.github.com/slard3/b1d824bcd28fab4e279fab6bf5d838d3)
[Logs](https://gist.github.com/slard3/4c12fe735b07a22ece731109371ed3b3)

I made an issue on Inspirations side first, thinking it was their fault, but turns out it wasn't lol
Shame on me, I can't read logs

KnightMiner/Inspirations#171
> Yep, found what I was looking for there:
> 
> ```
> Failed to register automatic subscribers. ModID: survive, class com.stereowalker.survive.Survive
> java.lang.NoClassDefFoundError: com/stereowalker/unionlib/util/ScreenHelper$ScreenOffset
> ```
> 
> Looks like a Survive bug, Inspirations just happened to get included in the stack trace because of the dumb Forge bug. I can add a safety there just so I stop getting blamed for all these exceptions though.
> 
> See KnightMiner/Inspirations#152 for more info on that

**Comment by Stereowalker** [comment]
Do you have UnionLib installed?

**Comment by slard3** [comment]
I thought I had everything updateddd, yet here I'm wasting everyone's time, I'm so sorry. But thanks for helping me out!
