### ISSUE TITLE
Feature request, compatibility with "serene seasons" mods?

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [Stereowalker/Survive#60]
Hi!

Since there might not be a tough as nails mod with working temperature system for 1.16 ( https://twitter.com/TheAdubbz/status/1356547262441091074?s=20 ) , would you consider adding compatibility for serene seasons mod?

Thank you for your time.

**Comment by iobiarg** [comment]
I would like this, but i think somehow it's working, because in Serene Season summer I get Hyperthermia as soon as I get in the beach with the iron armor....

**Comment by Stereowalker** [comment]
There already is compatibility with serene seasons
