### ISSUE TITLE
Temperature not working

### ISSUE THREAD

**Issue by zaze06** [Stereowalker/Survive#61]
Temperature not working in 1.16.5 version 3.1.3 forge 36.0.13 may just be my download of it.

**Comment by Stereowalker** [comment]
It's working, change the temperature render mode from HOTBAR to BAR in the client config to see the changes

**Comment by Stereowalker** [comment]
The file is in the config folder

**Comment by zaze06** [comment]
ok thx sorry for not being avelibel
