### ISSUE TITLE
[request] Purified water cooking / canteen crafting recipes

### ISSUE THREAD

**Issue by stfwi** [Stereowalker/Survive#62]
Hi Stereowalker, that mod is cool like hell, love it! I'd like to make a small recipe proposal for the purified water and canteen - basically that water can be cooked in a bucket, and that an empty canteen can be filled with one bucket or three bottles. (I just dump the file contents of the test datapack here in a code block, select 0 to 3 ;-) ). The result item NBT setting is a Forge extension.
(Versions for completeness: mc1.16.5 | forge-36.0.13 | survive-1.16.5-3.1.4). 
Keep up the good work! Cheers, wile.

*purified_water_bucket_cooking.json*
```
{
  "type": "minecraft:smelting",
  "ingredient": {
    "item": "minecraft:water_bucket"
  },
  "result": "survive:purified_water_bucket",
  "experience": 0.75,
  "cookingtime": 600
}
```

*purified_water_canteen_from_bottles.json*
```
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    { "item": "survive:purified_water_bottle" },
    { "item": "survive:purified_water_bottle" },
    { "item": "survive:purified_water_bottle" },
    { "item": "survive:canteen" }
  ],
  "result": {
    "item": "survive:purified_water_canteen",
    "nbt": { "DrinksLeft": 3 }
  }
}
```

*purified_water_canteen_from_bucket.json*
```
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    { "item": "survive:purified_water_bucket" },
    { "item": "survive:canteen" }
  ],
  "result": {
    "item": "survive:purified_water_canteen",
    "nbt": { "DrinksLeft": 3 }
  }
}
```

**Comment by stfwi** [comment]
Just realized the purified water bottles vanish when crafting, so this would need a change in the code - setting the container item of the purified water bottles to empty water bottles.

**Comment by Stereowalker** [comment]
Thanks
