### ISSUE TITLE
unionlib crash

### ISSUE THREAD

**Issue by Warbringer12** [Stereowalker/Survive#75]
one of my modpack players came across a crash when they loaded into a new world so I tested out just unionlib and survive only on fresh instance and it crashes 
[crash-2021-02-27_12.55.58-server.txt](https://github.com/Stereowalker/Survive/files/6055383/crash-2021-02-27_12.55.58-server.txt) this is the crash that appears

**Comment by AlyceOsbourne** [comment]
[latest.log](https://github.com/Stereowalker/Survive/files/6056102/latest.log)
[crash-2021-02-28_01.06.23-server.txt](https://github.com/Stereowalker/Survive/files/6056103/crash-2021-02-28_01.06.23-server.txt)
Also getting the same crash

**Comment by The-Arcanian** [comment]
I too am getting this crash.
https://gist.github.com/The-Arcanian/57b50a17df5821e3a921e8af66e346a0
I can add that the crash does not happen in creative, but if I switch game-mode to survival it will crash.

**Comment by NERD-NATO** [comment]
Is it overkill to add another crash report here? Ah, whatever, I'm getting the crash too. Just like The-Arcanian, it works fine until I switch to survival or try to create a survival world.
[crash-2021-03-08_12.14.56-server.txt](https://github.com/Stereowalker/Survive/files/6108613/crash-2021-03-08_12.14.56-server.txt)

**Comment by ghost** [comment]
Same issue
[crash.txt](https://github.com/Stereowalker/Survive/files/6108618/crash.txt)
Someone looked through it and apparently it has something to do with temperature stats from Unionlib(?)

**Comment by Stereowalker** [comment]
Update Survive to 3.1.7 and UnionLib to 3.2.6
