### ISSUE TITLE
[Server][3.1.6] Crash on start-up - java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by spxtator** [Stereowalker/Survive#80]
### Issue:

> **When my server is initializing mods, the server randomly crashes with:**

`java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER`

___________________________________________
### [Log:](https://pastebin.com/tdMgTjh1)

____________________________________________

### Specs:

* Forge: `forge-1.16.5-36.0.46`
* Java: `15.0.2`
* Tried Java versions: `11.0.10`

**Comment by Stereowalker** [comment]
Update to 3.1.7

**Comment by spxtator** [comment]
Thank you! 👍
