### ISSUE TITLE
Absorption hearts being ignored?

### ISSUE THREAD

**Issue by Wabbit0101** [Stereowalker/Survive#81]
**Forge: 1.16.5-36.0.1**
**UnionLib-1.16.5-3.2.4**
**Survive-1.16.5-3.1.6**

If player hasextra absorption hearts, those are not rendered (or are rendered empty) if either hypo or hyper thermia effects activated. Not sure if it's just rendering or the actually additional health is not being considered.

**Comment by Stereowalker** [comment]
It's perfectly intentional. They render like poison or wither render, which remove the absorption hearts

**Comment by Wabbit0101** [comment]
So I'm flagging this as it's just a rendering thing and the internal damage computation (not Survive's) will account for extra values.
