### ISSUE TITLE
Channel crash?

### ISSUE THREAD

**Issue by DcNdrew** [Stereowalker/Survive#82]
Mod File: Survive-1.16.5-3.1.7.jar
	Failure message: Survive (survive) has failed to load correctly
		java.lang.NoSuchFieldError: CHANNEL
	Mod Version: 1.16.5-3.1.7
	Mod Issue URL: https://github.com/Stereowalker/Survive/issues
	Exception message: java.lang.NoSuchFieldError: CHANNEL

**Comment by Stereowalker** [comment]
UnionLib version?

**Comment by DcNdrew** [comment]
Yup, that was the problem. :]
