### ISSUE TITLE
Shaking exhaustion bar

### ISSUE THREAD

**Issue by kubistonek** [Stereowalker/Survive#89]
when exhaustion bar is shaking (low exhaustion) there is anorther exhaustion bar behind it, but not shaking

**Comment by Stereowalker** [comment]
It really does seem that way, doesn't it? The only way to fix this issue is by changing the texture of the energy bars. It's because of the amount of black in the image

**Comment by Stereowalker** [comment]
You're going to have to deal with it until we find an alternative image that fill fix this
