### ISSUE TITLE
How to add new item to config

### ISSUE THREAD

**Issue by Gruszkomir** [Stereowalker/Survive#9]
Hello, I would like to add a new item from another mod to the configuration file, but every time I add the game, I won't even start. Could you show an example of a few items from other mods, e.g. pam hervestercraft. atmospheric:yucca_juice, pamhc2foodcore:sweetberryjuiceitem etc

**Comment by Stereowalker** [comment]
["pamhc2foodcore:sweetberryjuiceitem, 5", "atmospheric:yucca_juice, 3"]

**Comment by Stereowalker** [comment]
The numbers are the amount of thirst to be filled.
