### ISSUE TITLE
Temperature change should occur faster at abnormal temperatures

### ISSUE THREAD

**Issue by unmoving-javi** [Stereowalker/Survive#93]
This isn't a bug per se, but it'd make the mod a little bit more realistic. According to [Newton's Law of Cooling,](https://en.wikipedia.org/wiki/Newton%27s_law_of_cooling), which also applies to heating, the rate of change of temperature is proportional to the difference in temperature between the body and the surroundings.
In simpler words, when you're really hot and it's really cold, you'll cool down fast, but if you're slightly cold and it's slightly warm, you'll take more time to warm up.
While the actual mathematical specifics are probably too complex to implement, it'd be nice to see temperature decreasing quicker so as to recover from hyperthermia by entering cooler blocks (water, for instance) or to heat up faster by going near warmer blocks like lava.

**Comment by unmoving-javi** [comment]
This does seem to occur to _some_ extent in the current version, but cooling down and heating up is extremely difficult when you're at a high or low temp. Might be worth revising the logic around that.

**Comment by Stereowalker** [comment]
I may have no come across that law, but that is exactly the way heating and cooling works in the mod. It was designed that way to reduce the penalty for going near lava and also to make it easier to cool down. You can alter the speed at which temperature changes in the player with the config files
