### ISSUE TITLE
Mod Not Loading

### ISSUE THREAD

**Issue by MIGimmy** [Stereowalker/Survive#94]
Hi, I've been trying to use survive among a small 5-6 forge modpack for the last few days and it never loads right.  It always says there's a problem with the mod.  I saw a report on this problem that was about a month ago but it wasn't solved and the advice given to that person didn't help.  I'm using the latest versions of forge, survive and unionlib.
Here's the logs:
https://pastebin.com/BFiD90Nj

**Comment by smokedyt** [comment]
mine is having the same issue, i fixed all the problems besides a “channel error”. dk what to do

**Comment by Stereowalker** [comment]
@MIGimmy why are you running the 1.15.2 version of UnionLib

**Comment by Stereowalker** [comment]
@smokedyt Update your version of UnionLib
