### ISSUE TITLE
Survive (survive) has failed to load correctly. (java.lang.NoSuchFieldError: CHANNEL)

### ISSUE THREAD

**Issue by Bulwarini** [Stereowalker/Survive#99]
Okey so i get this error when i start minecraft what should i do? 
Here is latest log:
https://pastebin.com/TpJcjGuE
And crash log: 
https://pastebin.com/hNQyZ0SN
I am using minecraft forge 1.16.5-36.1.2
List of mods can be found here:
https://imgur.com/a/0s7qvFY

**Comment by DenisMasterHerobrine** [comment]
This is caused by an update of UnionLib with new config screen. Switch to UnionLib 3.2.6 for now until Survive will have an update for networking I think.
Same problem with UnionLib 3.3.0 and Survive 3.1.7 with this [crashlog](https://pastebin.com/y0d52dPW).

**Comment by Bulwarini** [comment]
So, i have switched to UnionLib 3.2.4 and Survive 3.1.6 and it WORKED. I tried higher versions but they pop-up some errors. Thanks for help.
